// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAuditLog = "audit_logs"

// AuditLog mapped from table <audit_logs>
type AuditLog struct {
	ID                    uint64    `gorm:"column:id;primaryKey;autoIncrement:true" json:""`
	ActorUserID           uint64    `gorm:"column:actor_user_id;not null" json:""`
	ActorUsernameSnapshot string    `gorm:"column:actor_username_snapshot;not null" json:""`
	Action                string    `gorm:"column:action;not null" json:""`
	TargetType            string    `gorm:"column:target_type;not null" json:""`
	TargetID              string    `gorm:"column:target_id;not null" json:""`
	TargetNameSnapshot    string    `gorm:"column:target_name_snapshot;not null" json:""`
	OccurredAt            time.Time `gorm:"column:occurred_at;not null" json:""`
	BeforeJSON            *string   `gorm:"column:before_json" json:""`
	AfterJSON             *string   `gorm:"column:after_json" json:""`
	Result                string    `gorm:"column:result;not null" json:""`
	IP                    *string   `gorm:"column:ip" json:""`
}

// TableName AuditLog's table name
func (*AuditLog) TableName() string {
	return TableNameAuditLog
}
