// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameEnvironment = "environments"

// Environment mapped from table <environments>
type Environment struct {
	ID          uint64    `gorm:"column:id;primaryKey;autoIncrement:true" json:""`
	Code        string    `gorm:"column:code;not null" json:""`
	Name        string    `gorm:"column:name;not null" json:""`
	Status      string    `gorm:"column:status;not null;default:active" json:""`
	Description *string   `gorm:"column:description" json:""`
	CreatedAt   time.Time `gorm:"column:created_at;not null" json:""`
	UpdatedAt   time.Time `gorm:"column:updated_at;not null" json:""`
}

// TableName Environment's table name
func (*Environment) TableName() string {
	return TableNameEnvironment
}
