// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameGrant = "grants"

// Grant mapped from table <grants>
type Grant struct {
	ID             uint64    `gorm:"column:id;primaryKey;autoIncrement:true" json:""`
	SubjectType    string    `gorm:"column:subject_type;not null" json:""`
	SubjectID      uint64    `gorm:"column:subject_id;not null" json:""`
	ObjectType     string    `gorm:"column:object_type;not null" json:""`
	ObjectID       uint64    `gorm:"column:object_id;not null" json:""`
	PermissionCode string    `gorm:"column:permission_code;not null" json:""`
	CreatedAt      time.Time `gorm:"column:created_at;not null" json:""`
	UpdatedAt      time.Time `gorm:"column:updated_at;not null" json:""`
}

// TableName Grant's table name
func (*Grant) TableName() string {
	return TableNameGrant
}
