// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameHost = "hosts"

// Host mapped from table <hosts>
type Host struct {
	ID              uint64    `gorm:"column:id;primaryKey;autoIncrement:true" json:""`
	Name            string    `gorm:"column:name;not null" json:""`
	Hostname        string    `gorm:"column:hostname;not null" json:""`
	PrimaryAddress  string    `gorm:"column:primary_address;not null" json:""`
	ProviderKind    string    `gorm:"column:provider_kind;not null" json:""`
	CloudVendor     *string   `gorm:"column:cloud_vendor" json:""`
	CloudInstanceID *string   `gorm:"column:cloud_instance_id" json:""`
	OsType          *string   `gorm:"column:os_type" json:""`
	Status          string    `gorm:"column:status;not null;default:active" json:""`
	LocationID      *uint64   `gorm:"column:location_id" json:""`
	Description     *string   `gorm:"column:description" json:""`
	CreatedAt       time.Time `gorm:"column:created_at;not null" json:""`
	UpdatedAt       time.Time `gorm:"column:updated_at;not null" json:""`
}

// TableName Host's table name
func (*Host) TableName() string {
	return TableNameHost
}
