// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameHostCredential = "host_credentials"

// HostCredential mapped from table <host_credentials>
type HostCredential struct {
	ID                       uint64    `gorm:"column:id;primaryKey;autoIncrement:true" json:""`
	HostID                   uint64    `gorm:"column:host_id;not null" json:""`
	AccountName              string    `gorm:"column:account_name;not null" json:""`
	CredentialName           string    `gorm:"column:credential_name;not null" json:""`
	CredentialKind           string    `gorm:"column:credential_kind;not null" json:""`
	Username                 *string   `gorm:"column:username" json:""`
	SecretCiphertext         *string   `gorm:"column:secret_ciphertext" json:""`
	CertificatePemCiphertext *string   `gorm:"column:certificate_pem_ciphertext" json:""`
	PrivateKeyPemCiphertext  *string   `gorm:"column:private_key_pem_ciphertext" json:""`
	PassphraseCiphertext     *string   `gorm:"column:passphrase_ciphertext" json:""`
	Status                   string    `gorm:"column:status;not null;default:active" json:""`
	Description              *string   `gorm:"column:description" json:""`
	CreatedAt                time.Time `gorm:"column:created_at;not null" json:""`
	UpdatedAt                time.Time `gorm:"column:updated_at;not null" json:""`
}

// TableName HostCredential's table name
func (*HostCredential) TableName() string {
	return TableNameHostCredential
}
