// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameHostEnvironment = "host_environments"

// HostEnvironment mapped from table <host_environments>
type HostEnvironment struct {
	ID            uint64    `gorm:"column:id;primaryKey;autoIncrement:true" json:""`
	HostID        uint64    `gorm:"column:host_id;not null" json:""`
	EnvironmentID uint64    `gorm:"column:environment_id;not null" json:""`
	CreatedAt     time.Time `gorm:"column:created_at;not null" json:""`
}

// TableName HostEnvironment's table name
func (*HostEnvironment) TableName() string {
	return TableNameHostEnvironment
}
