// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameLocation = "locations"

// Location mapped from table <locations>
type Location struct {
	ID           uint64    `gorm:"column:id;primaryKey;autoIncrement:true" json:""`
	Code         string    `gorm:"column:code;not null" json:""`
	Name         string    `gorm:"column:name;not null" json:""`
	LocationType string    `gorm:"column:location_type;not null" json:""`
	Address      *string   `gorm:"column:address" json:""`
	Status       string    `gorm:"column:status;not null;default:active" json:""`
	Description  *string   `gorm:"column:description" json:""`
	CreatedAt    time.Time `gorm:"column:created_at;not null" json:""`
	UpdatedAt    time.Time `gorm:"column:updated_at;not null" json:""`
}

// TableName Location's table name
func (*Location) TableName() string {
	return TableNameLocation
}
