// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePage = "pages"

// Page mapped from table <pages>
type Page struct {
	ID          uint64    `gorm:"column:id;primaryKey;autoIncrement:true" json:""`
	Name        string    `gorm:"column:name;not null" json:""`
	RoutePath   string    `gorm:"column:route_path;not null" json:""`
	Source      string    `gorm:"column:source;not null;default:manual" json:""`
	Status      string    `gorm:"column:status;not null;default:active" json:""`
	Description *string   `gorm:"column:description" json:""`
	CreatedAt   time.Time `gorm:"column:created_at;not null" json:""`
	UpdatedAt   time.Time `gorm:"column:updated_at;not null" json:""`
}

// TableName Page's table name
func (*Page) TableName() string {
	return TableNamePage
}
