// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePermissionDefinition = "permission_definitions"

// PermissionDefinition mapped from table <permission_definitions>
type PermissionDefinition struct {
	ID           uint64    `gorm:"column:id;primaryKey;autoIncrement:true" json:""`
	Code         string    `gorm:"column:code;not null" json:""`
	ObjectFamily string    `gorm:"column:object_family;not null" json:""`
	Action       string    `gorm:"column:action;not null" json:""`
	DisplayName  string    `gorm:"column:display_name;not null" json:""`
	Description  *string   `gorm:"column:description" json:""`
	Status       string    `gorm:"column:status;not null;default:active" json:""`
	CreatedAt    time.Time `gorm:"column:created_at;not null" json:""`
	UpdatedAt    time.Time `gorm:"column:updated_at;not null" json:""`
}

// TableName PermissionDefinition's table name
func (*PermissionDefinition) TableName() string {
	return TableNamePermissionDefinition
}
