// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameResourceGroup = "resource_groups"

// ResourceGroup compatibility storage: resource_groups
type ResourceGroup struct {
	ID          uint64    `gorm:"column:id;primaryKey;autoIncrement:true" json:""`
	Name        string    `gorm:"column:name;not null" json:""`
	Type        string    `gorm:"column:type;not null" json:""`
	Description *string   `gorm:"column:description" json:""`
	CreatedAt   time.Time `gorm:"column:created_at;not null" json:""`
	UpdatedAt   time.Time `gorm:"column:updated_at;not null" json:""`
}

// TableName ResourceGroup's table name
func (*ResourceGroup) TableName() string {
	return TableNameResourceGroup
}
