// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameResource = "resources"

// Resource compatibility storage: resources
type Resource struct {
	Key               uint64    `gorm:"column:key;primaryKey;autoIncrement:true" json:""`
	Name              string    `gorm:"column:name;not null" json:""`
	Type              string    `gorm:"column:type;not null" json:""`
	Address           *string   `gorm:"column:address" json:""`
	ServiceIdentifier *string   `gorm:"column:service_identifier" json:""`
	RoutePath         *string   `gorm:"column:route_path" json:""`
	Status            string    `gorm:"column:status;not null;default:active" json:""`
	Description       *string   `gorm:"column:description" json:""`
	CreatedAt         time.Time `gorm:"column:created_at;not null" json:""`
	UpdatedAt         time.Time `gorm:"column:updated_at;not null" json:""`
}

// TableName Resource's table name
func (*Resource) TableName() string {
	return TableNameResource
}
