// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameResourceGroupMember = "resource_group_members"

// ResourceGroupMember compatibility storage: resource_group_members
type ResourceGroupMember struct {
	ID              uint64    `gorm:"column:id;primaryKey;autoIncrement:true" json:""`
	ResourceKey     uint64    `gorm:"column:resource_key;not null" json:""`
	ResourceGroupID uint64    `gorm:"column:resource_group_id;not null" json:""`
	CreatedAt       time.Time `gorm:"column:created_at;not null" json:""`
}

// TableName ResourceGroupMember's table name
func (*ResourceGroupMember) TableName() string {
	return TableNameResourceGroupMember
}
