// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameServiceCredential = "service_credentials"

// ServiceCredential mapped from table <service_credentials>
type ServiceCredential struct {
	ID                       uint64    `gorm:"column:id;primaryKey;autoIncrement:true" json:""`
	ServiceID                uint64    `gorm:"column:service_id;not null" json:""`
	AccountName              string    `gorm:"column:account_name;not null" json:""`
	CredentialName           string    `gorm:"column:credential_name;not null" json:""`
	CredentialKind           string    `gorm:"column:credential_kind;not null" json:""`
	Username                 *string   `gorm:"column:username" json:""`
	SecretCiphertext         *string   `gorm:"column:secret_ciphertext" json:""`
	CertificatePemCiphertext *string   `gorm:"column:certificate_pem_ciphertext" json:""`
	PrivateKeyPemCiphertext  *string   `gorm:"column:private_key_pem_ciphertext" json:""`
	PassphraseCiphertext     *string   `gorm:"column:passphrase_ciphertext" json:""`
	Status                   string    `gorm:"column:status;not null;default:active" json:""`
	Description              *string   `gorm:"column:description" json:""`
	CreatedAt                time.Time `gorm:"column:created_at;not null" json:""`
	UpdatedAt                time.Time `gorm:"column:updated_at;not null" json:""`
}

// TableName ServiceCredential's table name
func (*ServiceCredential) TableName() string {
	return TableNameServiceCredential
}
