// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameServiceEnvironment = "service_environments"

// ServiceEnvironment mapped from table <service_environments>
type ServiceEnvironment struct {
	ID            uint64    `gorm:"column:id;primaryKey;autoIncrement:true" json:""`
	ServiceID     uint64    `gorm:"column:service_id;not null" json:""`
	EnvironmentID uint64    `gorm:"column:environment_id;not null" json:""`
	CreatedAt     time.Time `gorm:"column:created_at;not null" json:""`
}

// TableName ServiceEnvironment's table name
func (*ServiceEnvironment) TableName() string {
	return TableNameServiceEnvironment
}
