// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameService = "services"

// Service mapped from table <services>
type Service struct {
	ID                   uint64    `gorm:"column:id;primaryKey;autoIncrement:true" json:""`
	Name                 string    `gorm:"column:name;not null" json:""`
	ServiceKind          string    `gorm:"column:service_kind;not null" json:""`
	HostID               *uint64   `gorm:"column:host_id" json:""`
	EndpointOrIdentifier string    `gorm:"column:endpoint_or_identifier;not null" json:""`
	Port                 *int32    `gorm:"column:port" json:""`
	Protocol             *string   `gorm:"column:protocol" json:""`
	CloudVendor          *string   `gorm:"column:cloud_vendor" json:""`
	CloudProductCode     *string   `gorm:"column:cloud_product_code" json:""`
	Status               string    `gorm:"column:status;not null;default:active" json:""`
	Description          *string   `gorm:"column:description" json:""`
	CreatedAt            time.Time `gorm:"column:created_at;not null" json:""`
	UpdatedAt            time.Time `gorm:"column:updated_at;not null" json:""`
}

// TableName Service's table name
func (*Service) TableName() string {
	return TableNameService
}
