// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUserGroupMember = "user_group_members"

// UserGroupMember mapped from table <user_group_members>
type UserGroupMember struct {
	ID          uint64    `gorm:"column:id;primaryKey;autoIncrement:true" json:""`
	UserID      uint64    `gorm:"column:user_id;not null" json:""`
	UserGroupID uint64    `gorm:"column:user_group_id;not null" json:""`
	CreatedAt   time.Time `gorm:"column:created_at;not null" json:""`
}

// TableName UserGroupMember's table name
func (*UserGroupMember) TableName() string {
	return TableNameUserGroupMember
}
