// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUserGroup = "user_groups"

// UserGroup mapped from table <user_groups>
type UserGroup struct {
	ID          uint64    `gorm:"column:id;primaryKey;autoIncrement:true" json:""`
	Name        string    `gorm:"column:name;not null" json:""`
	Description *string   `gorm:"column:description" json:""`
	CreatedAt   time.Time `gorm:"column:created_at;not null" json:""`
	UpdatedAt   time.Time `gorm:"column:updated_at;not null" json:""`
}

// TableName UserGroup's table name
func (*UserGroup) TableName() string {
	return TableNameUserGroup
}
