// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	ID                 uint64    `gorm:"column:id;primaryKey;autoIncrement:true" json:""`
	Username           string    `gorm:"column:username;not null" json:""`
	PasswordHash       string    `gorm:"column:password_hash;not null" json:""`
	Role               string    `gorm:"column:role;not null;default:user" json:""`
	Status             string    `gorm:"column:status;not null;default:enabled" json:""`
	MustChangePassword bool      `gorm:"column:must_change_password;not null;default:1" json:""`
	CreatedAt          time.Time `gorm:"column:created_at;not null" json:""`
	UpdatedAt          time.Time `gorm:"column:updated_at;not null" json:""`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
