// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"irms/backend/internal/model"
)

func newAuditLog(db *gorm.DB, opts ...gen.DOOption) auditLog {
	_auditLog := auditLog{}

	_auditLog.auditLogDo.UseDB(db, opts...)
	_auditLog.auditLogDo.UseModel(&model.AuditLog{})

	tableName := _auditLog.auditLogDo.TableName()
	_auditLog.ALL = field.NewAsterisk(tableName)
	_auditLog.ID = field.NewUint64(tableName, "id")
	_auditLog.ActorUserID = field.NewUint64(tableName, "actor_user_id")
	_auditLog.ActorUsernameSnapshot = field.NewString(tableName, "actor_username_snapshot")
	_auditLog.Action = field.NewString(tableName, "action")
	_auditLog.TargetType = field.NewString(tableName, "target_type")
	_auditLog.TargetID = field.NewString(tableName, "target_id")
	_auditLog.TargetNameSnapshot = field.NewString(tableName, "target_name_snapshot")
	_auditLog.OccurredAt = field.NewTime(tableName, "occurred_at")
	_auditLog.BeforeJSON = field.NewString(tableName, "before_json")
	_auditLog.AfterJSON = field.NewString(tableName, "after_json")
	_auditLog.Result = field.NewString(tableName, "result")
	_auditLog.IP = field.NewString(tableName, "ip")

	_auditLog.fillFieldMap()

	return _auditLog
}

type auditLog struct {
	auditLogDo auditLogDo

	ALL                   field.Asterisk
	ID                    field.Uint64
	ActorUserID           field.Uint64
	ActorUsernameSnapshot field.String
	Action                field.String
	TargetType            field.String
	TargetID              field.String
	TargetNameSnapshot    field.String
	OccurredAt            field.Time
	BeforeJSON            field.String
	AfterJSON             field.String
	Result                field.String
	IP                    field.String

	fieldMap map[string]field.Expr
}

func (a auditLog) Table(newTableName string) *auditLog {
	a.auditLogDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a auditLog) As(alias string) *auditLog {
	a.auditLogDo.DO = *(a.auditLogDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *auditLog) updateTableName(table string) *auditLog {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewUint64(table, "id")
	a.ActorUserID = field.NewUint64(table, "actor_user_id")
	a.ActorUsernameSnapshot = field.NewString(table, "actor_username_snapshot")
	a.Action = field.NewString(table, "action")
	a.TargetType = field.NewString(table, "target_type")
	a.TargetID = field.NewString(table, "target_id")
	a.TargetNameSnapshot = field.NewString(table, "target_name_snapshot")
	a.OccurredAt = field.NewTime(table, "occurred_at")
	a.BeforeJSON = field.NewString(table, "before_json")
	a.AfterJSON = field.NewString(table, "after_json")
	a.Result = field.NewString(table, "result")
	a.IP = field.NewString(table, "ip")

	a.fillFieldMap()

	return a
}

func (a *auditLog) WithContext(ctx context.Context) IAuditLogDo { return a.auditLogDo.WithContext(ctx) }

func (a auditLog) TableName() string { return a.auditLogDo.TableName() }

func (a auditLog) Alias() string { return a.auditLogDo.Alias() }

func (a auditLog) Columns(cols ...field.Expr) gen.Columns { return a.auditLogDo.Columns(cols...) }

func (a *auditLog) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *auditLog) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 12)
	a.fieldMap["id"] = a.ID
	a.fieldMap["actor_user_id"] = a.ActorUserID
	a.fieldMap["actor_username_snapshot"] = a.ActorUsernameSnapshot
	a.fieldMap["action"] = a.Action
	a.fieldMap["target_type"] = a.TargetType
	a.fieldMap["target_id"] = a.TargetID
	a.fieldMap["target_name_snapshot"] = a.TargetNameSnapshot
	a.fieldMap["occurred_at"] = a.OccurredAt
	a.fieldMap["before_json"] = a.BeforeJSON
	a.fieldMap["after_json"] = a.AfterJSON
	a.fieldMap["result"] = a.Result
	a.fieldMap["ip"] = a.IP
}

func (a auditLog) clone(db *gorm.DB) auditLog {
	a.auditLogDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a auditLog) replaceDB(db *gorm.DB) auditLog {
	a.auditLogDo.ReplaceDB(db)
	return a
}

type auditLogDo struct{ gen.DO }

type IAuditLogDo interface {
	gen.SubQuery
	Debug() IAuditLogDo
	WithContext(ctx context.Context) IAuditLogDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IAuditLogDo
	WriteDB() IAuditLogDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IAuditLogDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IAuditLogDo
	Not(conds ...gen.Condition) IAuditLogDo
	Or(conds ...gen.Condition) IAuditLogDo
	Select(conds ...field.Expr) IAuditLogDo
	Where(conds ...gen.Condition) IAuditLogDo
	Order(conds ...field.Expr) IAuditLogDo
	Distinct(cols ...field.Expr) IAuditLogDo
	Omit(cols ...field.Expr) IAuditLogDo
	Join(table schema.Tabler, on ...field.Expr) IAuditLogDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IAuditLogDo
	RightJoin(table schema.Tabler, on ...field.Expr) IAuditLogDo
	Group(cols ...field.Expr) IAuditLogDo
	Having(conds ...gen.Condition) IAuditLogDo
	Limit(limit int) IAuditLogDo
	Offset(offset int) IAuditLogDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IAuditLogDo
	Unscoped() IAuditLogDo
	Create(values ...*model.AuditLog) error
	CreateInBatches(values []*model.AuditLog, batchSize int) error
	Save(values ...*model.AuditLog) error
	First() (*model.AuditLog, error)
	Take() (*model.AuditLog, error)
	Last() (*model.AuditLog, error)
	Find() ([]*model.AuditLog, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AuditLog, err error)
	FindInBatches(result *[]*model.AuditLog, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.AuditLog) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IAuditLogDo
	Assign(attrs ...field.AssignExpr) IAuditLogDo
	Joins(fields ...field.RelationField) IAuditLogDo
	Preload(fields ...field.RelationField) IAuditLogDo
	FirstOrInit() (*model.AuditLog, error)
	FirstOrCreate() (*model.AuditLog, error)
	FindByPage(offset int, limit int) (result []*model.AuditLog, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IAuditLogDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (a auditLogDo) Debug() IAuditLogDo {
	return a.withDO(a.DO.Debug())
}

func (a auditLogDo) WithContext(ctx context.Context) IAuditLogDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a auditLogDo) ReadDB() IAuditLogDo {
	return a.Clauses(dbresolver.Read)
}

func (a auditLogDo) WriteDB() IAuditLogDo {
	return a.Clauses(dbresolver.Write)
}

func (a auditLogDo) Session(config *gorm.Session) IAuditLogDo {
	return a.withDO(a.DO.Session(config))
}

func (a auditLogDo) Clauses(conds ...clause.Expression) IAuditLogDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a auditLogDo) Returning(value interface{}, columns ...string) IAuditLogDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a auditLogDo) Not(conds ...gen.Condition) IAuditLogDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a auditLogDo) Or(conds ...gen.Condition) IAuditLogDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a auditLogDo) Select(conds ...field.Expr) IAuditLogDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a auditLogDo) Where(conds ...gen.Condition) IAuditLogDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a auditLogDo) Order(conds ...field.Expr) IAuditLogDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a auditLogDo) Distinct(cols ...field.Expr) IAuditLogDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a auditLogDo) Omit(cols ...field.Expr) IAuditLogDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a auditLogDo) Join(table schema.Tabler, on ...field.Expr) IAuditLogDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a auditLogDo) LeftJoin(table schema.Tabler, on ...field.Expr) IAuditLogDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a auditLogDo) RightJoin(table schema.Tabler, on ...field.Expr) IAuditLogDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a auditLogDo) Group(cols ...field.Expr) IAuditLogDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a auditLogDo) Having(conds ...gen.Condition) IAuditLogDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a auditLogDo) Limit(limit int) IAuditLogDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a auditLogDo) Offset(offset int) IAuditLogDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a auditLogDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IAuditLogDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a auditLogDo) Unscoped() IAuditLogDo {
	return a.withDO(a.DO.Unscoped())
}

func (a auditLogDo) Create(values ...*model.AuditLog) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a auditLogDo) CreateInBatches(values []*model.AuditLog, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a auditLogDo) Save(values ...*model.AuditLog) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a auditLogDo) First() (*model.AuditLog, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.AuditLog), nil
	}
}

func (a auditLogDo) Take() (*model.AuditLog, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.AuditLog), nil
	}
}

func (a auditLogDo) Last() (*model.AuditLog, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.AuditLog), nil
	}
}

func (a auditLogDo) Find() ([]*model.AuditLog, error) {
	result, err := a.DO.Find()
	return result.([]*model.AuditLog), err
}

func (a auditLogDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AuditLog, err error) {
	buf := make([]*model.AuditLog, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a auditLogDo) FindInBatches(result *[]*model.AuditLog, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a auditLogDo) Attrs(attrs ...field.AssignExpr) IAuditLogDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a auditLogDo) Assign(attrs ...field.AssignExpr) IAuditLogDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a auditLogDo) Joins(fields ...field.RelationField) IAuditLogDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a auditLogDo) Preload(fields ...field.RelationField) IAuditLogDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a auditLogDo) FirstOrInit() (*model.AuditLog, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.AuditLog), nil
	}
}

func (a auditLogDo) FirstOrCreate() (*model.AuditLog, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.AuditLog), nil
	}
}

func (a auditLogDo) FindByPage(offset int, limit int) (result []*model.AuditLog, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a auditLogDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a auditLogDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a auditLogDo) Delete(models ...*model.AuditLog) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *auditLogDo) withDO(do gen.Dao) *auditLogDo {
	a.DO = *do.(*gen.DO)
	return a
}
