// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q                    = new(Query)
	AuditLog             *auditLog
	Environment          *environment
	Grant                *grant
	Host                 *host
	HostCredential       *hostCredential
	HostEnvironment      *hostEnvironment
	Location             *location
	Page                 *page
	PermissionDefinition *permissionDefinition
	Resource             *resource
	ResourceGroup        *resourceGroup
	ResourceGroupMember  *resourceGroupMember
	Service              *service
	ServiceCredential    *serviceCredential
	ServiceEnvironment   *serviceEnvironment
	User                 *user
	UserGroup            *userGroup
	UserGroupMember      *userGroupMember
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	AuditLog = &Q.AuditLog
	Environment = &Q.Environment
	Grant = &Q.Grant
	Host = &Q.Host
	HostCredential = &Q.HostCredential
	HostEnvironment = &Q.HostEnvironment
	Location = &Q.Location
	Page = &Q.Page
	PermissionDefinition = &Q.PermissionDefinition
	Resource = &Q.Resource
	ResourceGroup = &Q.ResourceGroup
	ResourceGroupMember = &Q.ResourceGroupMember
	Service = &Q.Service
	ServiceCredential = &Q.ServiceCredential
	ServiceEnvironment = &Q.ServiceEnvironment
	User = &Q.User
	UserGroup = &Q.UserGroup
	UserGroupMember = &Q.UserGroupMember
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:                   db,
		AuditLog:             newAuditLog(db, opts...),
		Environment:          newEnvironment(db, opts...),
		Grant:                newGrant(db, opts...),
		Host:                 newHost(db, opts...),
		HostCredential:       newHostCredential(db, opts...),
		HostEnvironment:      newHostEnvironment(db, opts...),
		Location:             newLocation(db, opts...),
		Page:                 newPage(db, opts...),
		PermissionDefinition: newPermissionDefinition(db, opts...),
		Resource:             newResource(db, opts...),
		ResourceGroup:        newResourceGroup(db, opts...),
		ResourceGroupMember:  newResourceGroupMember(db, opts...),
		Service:              newService(db, opts...),
		ServiceCredential:    newServiceCredential(db, opts...),
		ServiceEnvironment:   newServiceEnvironment(db, opts...),
		User:                 newUser(db, opts...),
		UserGroup:            newUserGroup(db, opts...),
		UserGroupMember:      newUserGroupMember(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	AuditLog             auditLog
	Environment          environment
	Grant                grant
	Host                 host
	HostCredential       hostCredential
	HostEnvironment      hostEnvironment
	Location             location
	Page                 page
	PermissionDefinition permissionDefinition
	Resource             resource
	ResourceGroup        resourceGroup
	ResourceGroupMember  resourceGroupMember
	Service              service
	ServiceCredential    serviceCredential
	ServiceEnvironment   serviceEnvironment
	User                 user
	UserGroup            userGroup
	UserGroupMember      userGroupMember
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:                   db,
		AuditLog:             q.AuditLog.clone(db),
		Environment:          q.Environment.clone(db),
		Grant:                q.Grant.clone(db),
		Host:                 q.Host.clone(db),
		HostCredential:       q.HostCredential.clone(db),
		HostEnvironment:      q.HostEnvironment.clone(db),
		Location:             q.Location.clone(db),
		Page:                 q.Page.clone(db),
		PermissionDefinition: q.PermissionDefinition.clone(db),
		Resource:             q.Resource.clone(db),
		ResourceGroup:        q.ResourceGroup.clone(db),
		ResourceGroupMember:  q.ResourceGroupMember.clone(db),
		Service:              q.Service.clone(db),
		ServiceCredential:    q.ServiceCredential.clone(db),
		ServiceEnvironment:   q.ServiceEnvironment.clone(db),
		User:                 q.User.clone(db),
		UserGroup:            q.UserGroup.clone(db),
		UserGroupMember:      q.UserGroupMember.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:                   db,
		AuditLog:             q.AuditLog.replaceDB(db),
		Environment:          q.Environment.replaceDB(db),
		Grant:                q.Grant.replaceDB(db),
		Host:                 q.Host.replaceDB(db),
		HostCredential:       q.HostCredential.replaceDB(db),
		HostEnvironment:      q.HostEnvironment.replaceDB(db),
		Location:             q.Location.replaceDB(db),
		Page:                 q.Page.replaceDB(db),
		PermissionDefinition: q.PermissionDefinition.replaceDB(db),
		Resource:             q.Resource.replaceDB(db),
		ResourceGroup:        q.ResourceGroup.replaceDB(db),
		ResourceGroupMember:  q.ResourceGroupMember.replaceDB(db),
		Service:              q.Service.replaceDB(db),
		ServiceCredential:    q.ServiceCredential.replaceDB(db),
		ServiceEnvironment:   q.ServiceEnvironment.replaceDB(db),
		User:                 q.User.replaceDB(db),
		UserGroup:            q.UserGroup.replaceDB(db),
		UserGroupMember:      q.UserGroupMember.replaceDB(db),
	}
}

type queryCtx struct {
	AuditLog             IAuditLogDo
	Environment          IEnvironmentDo
	Grant                IGrantDo
	Host                 IHostDo
	HostCredential       IHostCredentialDo
	HostEnvironment      IHostEnvironmentDo
	Location             ILocationDo
	Page                 IPageDo
	PermissionDefinition IPermissionDefinitionDo
	Resource             IResourceDo
	ResourceGroup        IResourceGroupDo
	ResourceGroupMember  IResourceGroupMemberDo
	Service              IServiceDo
	ServiceCredential    IServiceCredentialDo
	ServiceEnvironment   IServiceEnvironmentDo
	User                 IUserDo
	UserGroup            IUserGroupDo
	UserGroupMember      IUserGroupMemberDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		AuditLog:             q.AuditLog.WithContext(ctx),
		Environment:          q.Environment.WithContext(ctx),
		Grant:                q.Grant.WithContext(ctx),
		Host:                 q.Host.WithContext(ctx),
		HostCredential:       q.HostCredential.WithContext(ctx),
		HostEnvironment:      q.HostEnvironment.WithContext(ctx),
		Location:             q.Location.WithContext(ctx),
		Page:                 q.Page.WithContext(ctx),
		PermissionDefinition: q.PermissionDefinition.WithContext(ctx),
		Resource:             q.Resource.WithContext(ctx),
		ResourceGroup:        q.ResourceGroup.WithContext(ctx),
		ResourceGroupMember:  q.ResourceGroupMember.WithContext(ctx),
		Service:              q.Service.WithContext(ctx),
		ServiceCredential:    q.ServiceCredential.WithContext(ctx),
		ServiceEnvironment:   q.ServiceEnvironment.WithContext(ctx),
		User:                 q.User.WithContext(ctx),
		UserGroup:            q.UserGroup.WithContext(ctx),
		UserGroupMember:      q.UserGroupMember.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
