// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"irms/backend/internal/model"
)

func newGrant(db *gorm.DB, opts ...gen.DOOption) grant {
	_grant := grant{}

	_grant.grantDo.UseDB(db, opts...)
	_grant.grantDo.UseModel(&model.Grant{})

	tableName := _grant.grantDo.TableName()
	_grant.ALL = field.NewAsterisk(tableName)
	_grant.ID = field.NewUint64(tableName, "id")
	_grant.SubjectType = field.NewString(tableName, "subject_type")
	_grant.SubjectID = field.NewUint64(tableName, "subject_id")
	_grant.ObjectType = field.NewString(tableName, "object_type")
	_grant.ObjectID = field.NewUint64(tableName, "object_id")
	_grant.PermissionCode = field.NewString(tableName, "permission_code")
	_grant.CreatedAt = field.NewTime(tableName, "created_at")
	_grant.UpdatedAt = field.NewTime(tableName, "updated_at")

	_grant.fillFieldMap()

	return _grant
}

type grant struct {
	grantDo grantDo

	ALL            field.Asterisk
	ID             field.Uint64
	SubjectType    field.String
	SubjectID      field.Uint64
	ObjectType     field.String
	ObjectID       field.Uint64
	PermissionCode field.String
	CreatedAt      field.Time
	UpdatedAt      field.Time

	fieldMap map[string]field.Expr
}

func (g grant) Table(newTableName string) *grant {
	g.grantDo.UseTable(newTableName)
	return g.updateTableName(newTableName)
}

func (g grant) As(alias string) *grant {
	g.grantDo.DO = *(g.grantDo.As(alias).(*gen.DO))
	return g.updateTableName(alias)
}

func (g *grant) updateTableName(table string) *grant {
	g.ALL = field.NewAsterisk(table)
	g.ID = field.NewUint64(table, "id")
	g.SubjectType = field.NewString(table, "subject_type")
	g.SubjectID = field.NewUint64(table, "subject_id")
	g.ObjectType = field.NewString(table, "object_type")
	g.ObjectID = field.NewUint64(table, "object_id")
	g.PermissionCode = field.NewString(table, "permission_code")
	g.CreatedAt = field.NewTime(table, "created_at")
	g.UpdatedAt = field.NewTime(table, "updated_at")

	g.fillFieldMap()

	return g
}

func (g *grant) WithContext(ctx context.Context) IGrantDo { return g.grantDo.WithContext(ctx) }

func (g grant) TableName() string { return g.grantDo.TableName() }

func (g grant) Alias() string { return g.grantDo.Alias() }

func (g grant) Columns(cols ...field.Expr) gen.Columns { return g.grantDo.Columns(cols...) }

func (g *grant) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := g.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (g *grant) fillFieldMap() {
	g.fieldMap = make(map[string]field.Expr, 8)
	g.fieldMap["id"] = g.ID
	g.fieldMap["subject_type"] = g.SubjectType
	g.fieldMap["subject_id"] = g.SubjectID
	g.fieldMap["object_type"] = g.ObjectType
	g.fieldMap["object_id"] = g.ObjectID
	g.fieldMap["permission_code"] = g.PermissionCode
	g.fieldMap["created_at"] = g.CreatedAt
	g.fieldMap["updated_at"] = g.UpdatedAt
}

func (g grant) clone(db *gorm.DB) grant {
	g.grantDo.ReplaceConnPool(db.Statement.ConnPool)
	return g
}

func (g grant) replaceDB(db *gorm.DB) grant {
	g.grantDo.ReplaceDB(db)
	return g
}

type grantDo struct{ gen.DO }

type IGrantDo interface {
	gen.SubQuery
	Debug() IGrantDo
	WithContext(ctx context.Context) IGrantDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IGrantDo
	WriteDB() IGrantDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IGrantDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IGrantDo
	Not(conds ...gen.Condition) IGrantDo
	Or(conds ...gen.Condition) IGrantDo
	Select(conds ...field.Expr) IGrantDo
	Where(conds ...gen.Condition) IGrantDo
	Order(conds ...field.Expr) IGrantDo
	Distinct(cols ...field.Expr) IGrantDo
	Omit(cols ...field.Expr) IGrantDo
	Join(table schema.Tabler, on ...field.Expr) IGrantDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IGrantDo
	RightJoin(table schema.Tabler, on ...field.Expr) IGrantDo
	Group(cols ...field.Expr) IGrantDo
	Having(conds ...gen.Condition) IGrantDo
	Limit(limit int) IGrantDo
	Offset(offset int) IGrantDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IGrantDo
	Unscoped() IGrantDo
	Create(values ...*model.Grant) error
	CreateInBatches(values []*model.Grant, batchSize int) error
	Save(values ...*model.Grant) error
	First() (*model.Grant, error)
	Take() (*model.Grant, error)
	Last() (*model.Grant, error)
	Find() ([]*model.Grant, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Grant, err error)
	FindInBatches(result *[]*model.Grant, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Grant) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IGrantDo
	Assign(attrs ...field.AssignExpr) IGrantDo
	Joins(fields ...field.RelationField) IGrantDo
	Preload(fields ...field.RelationField) IGrantDo
	FirstOrInit() (*model.Grant, error)
	FirstOrCreate() (*model.Grant, error)
	FindByPage(offset int, limit int) (result []*model.Grant, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IGrantDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (g grantDo) Debug() IGrantDo {
	return g.withDO(g.DO.Debug())
}

func (g grantDo) WithContext(ctx context.Context) IGrantDo {
	return g.withDO(g.DO.WithContext(ctx))
}

func (g grantDo) ReadDB() IGrantDo {
	return g.Clauses(dbresolver.Read)
}

func (g grantDo) WriteDB() IGrantDo {
	return g.Clauses(dbresolver.Write)
}

func (g grantDo) Session(config *gorm.Session) IGrantDo {
	return g.withDO(g.DO.Session(config))
}

func (g grantDo) Clauses(conds ...clause.Expression) IGrantDo {
	return g.withDO(g.DO.Clauses(conds...))
}

func (g grantDo) Returning(value interface{}, columns ...string) IGrantDo {
	return g.withDO(g.DO.Returning(value, columns...))
}

func (g grantDo) Not(conds ...gen.Condition) IGrantDo {
	return g.withDO(g.DO.Not(conds...))
}

func (g grantDo) Or(conds ...gen.Condition) IGrantDo {
	return g.withDO(g.DO.Or(conds...))
}

func (g grantDo) Select(conds ...field.Expr) IGrantDo {
	return g.withDO(g.DO.Select(conds...))
}

func (g grantDo) Where(conds ...gen.Condition) IGrantDo {
	return g.withDO(g.DO.Where(conds...))
}

func (g grantDo) Order(conds ...field.Expr) IGrantDo {
	return g.withDO(g.DO.Order(conds...))
}

func (g grantDo) Distinct(cols ...field.Expr) IGrantDo {
	return g.withDO(g.DO.Distinct(cols...))
}

func (g grantDo) Omit(cols ...field.Expr) IGrantDo {
	return g.withDO(g.DO.Omit(cols...))
}

func (g grantDo) Join(table schema.Tabler, on ...field.Expr) IGrantDo {
	return g.withDO(g.DO.Join(table, on...))
}

func (g grantDo) LeftJoin(table schema.Tabler, on ...field.Expr) IGrantDo {
	return g.withDO(g.DO.LeftJoin(table, on...))
}

func (g grantDo) RightJoin(table schema.Tabler, on ...field.Expr) IGrantDo {
	return g.withDO(g.DO.RightJoin(table, on...))
}

func (g grantDo) Group(cols ...field.Expr) IGrantDo {
	return g.withDO(g.DO.Group(cols...))
}

func (g grantDo) Having(conds ...gen.Condition) IGrantDo {
	return g.withDO(g.DO.Having(conds...))
}

func (g grantDo) Limit(limit int) IGrantDo {
	return g.withDO(g.DO.Limit(limit))
}

func (g grantDo) Offset(offset int) IGrantDo {
	return g.withDO(g.DO.Offset(offset))
}

func (g grantDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IGrantDo {
	return g.withDO(g.DO.Scopes(funcs...))
}

func (g grantDo) Unscoped() IGrantDo {
	return g.withDO(g.DO.Unscoped())
}

func (g grantDo) Create(values ...*model.Grant) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Create(values)
}

func (g grantDo) CreateInBatches(values []*model.Grant, batchSize int) error {
	return g.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (g grantDo) Save(values ...*model.Grant) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Save(values)
}

func (g grantDo) First() (*model.Grant, error) {
	if result, err := g.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Grant), nil
	}
}

func (g grantDo) Take() (*model.Grant, error) {
	if result, err := g.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Grant), nil
	}
}

func (g grantDo) Last() (*model.Grant, error) {
	if result, err := g.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Grant), nil
	}
}

func (g grantDo) Find() ([]*model.Grant, error) {
	result, err := g.DO.Find()
	return result.([]*model.Grant), err
}

func (g grantDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Grant, err error) {
	buf := make([]*model.Grant, 0, batchSize)
	err = g.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (g grantDo) FindInBatches(result *[]*model.Grant, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return g.DO.FindInBatches(result, batchSize, fc)
}

func (g grantDo) Attrs(attrs ...field.AssignExpr) IGrantDo {
	return g.withDO(g.DO.Attrs(attrs...))
}

func (g grantDo) Assign(attrs ...field.AssignExpr) IGrantDo {
	return g.withDO(g.DO.Assign(attrs...))
}

func (g grantDo) Joins(fields ...field.RelationField) IGrantDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Joins(_f))
	}
	return &g
}

func (g grantDo) Preload(fields ...field.RelationField) IGrantDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Preload(_f))
	}
	return &g
}

func (g grantDo) FirstOrInit() (*model.Grant, error) {
	if result, err := g.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Grant), nil
	}
}

func (g grantDo) FirstOrCreate() (*model.Grant, error) {
	if result, err := g.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Grant), nil
	}
}

func (g grantDo) FindByPage(offset int, limit int) (result []*model.Grant, count int64, err error) {
	result, err = g.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = g.Offset(-1).Limit(-1).Count()
	return
}

func (g grantDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = g.Count()
	if err != nil {
		return
	}

	err = g.Offset(offset).Limit(limit).Scan(result)
	return
}

func (g grantDo) Scan(result interface{}) (err error) {
	return g.DO.Scan(result)
}

func (g grantDo) Delete(models ...*model.Grant) (result gen.ResultInfo, err error) {
	return g.DO.Delete(models)
}

func (g *grantDo) withDO(do gen.Dao) *grantDo {
	g.DO = *do.(*gen.DO)
	return g
}
