// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"irms/backend/internal/model"
)

func newHostEnvironment(db *gorm.DB, opts ...gen.DOOption) hostEnvironment {
	_hostEnvironment := hostEnvironment{}

	_hostEnvironment.hostEnvironmentDo.UseDB(db, opts...)
	_hostEnvironment.hostEnvironmentDo.UseModel(&model.HostEnvironment{})

	tableName := _hostEnvironment.hostEnvironmentDo.TableName()
	_hostEnvironment.ALL = field.NewAsterisk(tableName)
	_hostEnvironment.ID = field.NewUint64(tableName, "id")
	_hostEnvironment.HostID = field.NewUint64(tableName, "host_id")
	_hostEnvironment.EnvironmentID = field.NewUint64(tableName, "environment_id")
	_hostEnvironment.CreatedAt = field.NewTime(tableName, "created_at")

	_hostEnvironment.fillFieldMap()

	return _hostEnvironment
}

type hostEnvironment struct {
	hostEnvironmentDo hostEnvironmentDo

	ALL           field.Asterisk
	ID            field.Uint64
	HostID        field.Uint64
	EnvironmentID field.Uint64
	CreatedAt     field.Time

	fieldMap map[string]field.Expr
}

func (h hostEnvironment) Table(newTableName string) *hostEnvironment {
	h.hostEnvironmentDo.UseTable(newTableName)
	return h.updateTableName(newTableName)
}

func (h hostEnvironment) As(alias string) *hostEnvironment {
	h.hostEnvironmentDo.DO = *(h.hostEnvironmentDo.As(alias).(*gen.DO))
	return h.updateTableName(alias)
}

func (h *hostEnvironment) updateTableName(table string) *hostEnvironment {
	h.ALL = field.NewAsterisk(table)
	h.ID = field.NewUint64(table, "id")
	h.HostID = field.NewUint64(table, "host_id")
	h.EnvironmentID = field.NewUint64(table, "environment_id")
	h.CreatedAt = field.NewTime(table, "created_at")

	h.fillFieldMap()

	return h
}

func (h *hostEnvironment) WithContext(ctx context.Context) IHostEnvironmentDo {
	return h.hostEnvironmentDo.WithContext(ctx)
}

func (h hostEnvironment) TableName() string { return h.hostEnvironmentDo.TableName() }

func (h hostEnvironment) Alias() string { return h.hostEnvironmentDo.Alias() }

func (h hostEnvironment) Columns(cols ...field.Expr) gen.Columns {
	return h.hostEnvironmentDo.Columns(cols...)
}

func (h *hostEnvironment) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := h.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (h *hostEnvironment) fillFieldMap() {
	h.fieldMap = make(map[string]field.Expr, 4)
	h.fieldMap["id"] = h.ID
	h.fieldMap["host_id"] = h.HostID
	h.fieldMap["environment_id"] = h.EnvironmentID
	h.fieldMap["created_at"] = h.CreatedAt
}

func (h hostEnvironment) clone(db *gorm.DB) hostEnvironment {
	h.hostEnvironmentDo.ReplaceConnPool(db.Statement.ConnPool)
	return h
}

func (h hostEnvironment) replaceDB(db *gorm.DB) hostEnvironment {
	h.hostEnvironmentDo.ReplaceDB(db)
	return h
}

type hostEnvironmentDo struct{ gen.DO }

type IHostEnvironmentDo interface {
	gen.SubQuery
	Debug() IHostEnvironmentDo
	WithContext(ctx context.Context) IHostEnvironmentDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IHostEnvironmentDo
	WriteDB() IHostEnvironmentDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IHostEnvironmentDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IHostEnvironmentDo
	Not(conds ...gen.Condition) IHostEnvironmentDo
	Or(conds ...gen.Condition) IHostEnvironmentDo
	Select(conds ...field.Expr) IHostEnvironmentDo
	Where(conds ...gen.Condition) IHostEnvironmentDo
	Order(conds ...field.Expr) IHostEnvironmentDo
	Distinct(cols ...field.Expr) IHostEnvironmentDo
	Omit(cols ...field.Expr) IHostEnvironmentDo
	Join(table schema.Tabler, on ...field.Expr) IHostEnvironmentDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IHostEnvironmentDo
	RightJoin(table schema.Tabler, on ...field.Expr) IHostEnvironmentDo
	Group(cols ...field.Expr) IHostEnvironmentDo
	Having(conds ...gen.Condition) IHostEnvironmentDo
	Limit(limit int) IHostEnvironmentDo
	Offset(offset int) IHostEnvironmentDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IHostEnvironmentDo
	Unscoped() IHostEnvironmentDo
	Create(values ...*model.HostEnvironment) error
	CreateInBatches(values []*model.HostEnvironment, batchSize int) error
	Save(values ...*model.HostEnvironment) error
	First() (*model.HostEnvironment, error)
	Take() (*model.HostEnvironment, error)
	Last() (*model.HostEnvironment, error)
	Find() ([]*model.HostEnvironment, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.HostEnvironment, err error)
	FindInBatches(result *[]*model.HostEnvironment, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.HostEnvironment) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IHostEnvironmentDo
	Assign(attrs ...field.AssignExpr) IHostEnvironmentDo
	Joins(fields ...field.RelationField) IHostEnvironmentDo
	Preload(fields ...field.RelationField) IHostEnvironmentDo
	FirstOrInit() (*model.HostEnvironment, error)
	FirstOrCreate() (*model.HostEnvironment, error)
	FindByPage(offset int, limit int) (result []*model.HostEnvironment, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IHostEnvironmentDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (h hostEnvironmentDo) Debug() IHostEnvironmentDo {
	return h.withDO(h.DO.Debug())
}

func (h hostEnvironmentDo) WithContext(ctx context.Context) IHostEnvironmentDo {
	return h.withDO(h.DO.WithContext(ctx))
}

func (h hostEnvironmentDo) ReadDB() IHostEnvironmentDo {
	return h.Clauses(dbresolver.Read)
}

func (h hostEnvironmentDo) WriteDB() IHostEnvironmentDo {
	return h.Clauses(dbresolver.Write)
}

func (h hostEnvironmentDo) Session(config *gorm.Session) IHostEnvironmentDo {
	return h.withDO(h.DO.Session(config))
}

func (h hostEnvironmentDo) Clauses(conds ...clause.Expression) IHostEnvironmentDo {
	return h.withDO(h.DO.Clauses(conds...))
}

func (h hostEnvironmentDo) Returning(value interface{}, columns ...string) IHostEnvironmentDo {
	return h.withDO(h.DO.Returning(value, columns...))
}

func (h hostEnvironmentDo) Not(conds ...gen.Condition) IHostEnvironmentDo {
	return h.withDO(h.DO.Not(conds...))
}

func (h hostEnvironmentDo) Or(conds ...gen.Condition) IHostEnvironmentDo {
	return h.withDO(h.DO.Or(conds...))
}

func (h hostEnvironmentDo) Select(conds ...field.Expr) IHostEnvironmentDo {
	return h.withDO(h.DO.Select(conds...))
}

func (h hostEnvironmentDo) Where(conds ...gen.Condition) IHostEnvironmentDo {
	return h.withDO(h.DO.Where(conds...))
}

func (h hostEnvironmentDo) Order(conds ...field.Expr) IHostEnvironmentDo {
	return h.withDO(h.DO.Order(conds...))
}

func (h hostEnvironmentDo) Distinct(cols ...field.Expr) IHostEnvironmentDo {
	return h.withDO(h.DO.Distinct(cols...))
}

func (h hostEnvironmentDo) Omit(cols ...field.Expr) IHostEnvironmentDo {
	return h.withDO(h.DO.Omit(cols...))
}

func (h hostEnvironmentDo) Join(table schema.Tabler, on ...field.Expr) IHostEnvironmentDo {
	return h.withDO(h.DO.Join(table, on...))
}

func (h hostEnvironmentDo) LeftJoin(table schema.Tabler, on ...field.Expr) IHostEnvironmentDo {
	return h.withDO(h.DO.LeftJoin(table, on...))
}

func (h hostEnvironmentDo) RightJoin(table schema.Tabler, on ...field.Expr) IHostEnvironmentDo {
	return h.withDO(h.DO.RightJoin(table, on...))
}

func (h hostEnvironmentDo) Group(cols ...field.Expr) IHostEnvironmentDo {
	return h.withDO(h.DO.Group(cols...))
}

func (h hostEnvironmentDo) Having(conds ...gen.Condition) IHostEnvironmentDo {
	return h.withDO(h.DO.Having(conds...))
}

func (h hostEnvironmentDo) Limit(limit int) IHostEnvironmentDo {
	return h.withDO(h.DO.Limit(limit))
}

func (h hostEnvironmentDo) Offset(offset int) IHostEnvironmentDo {
	return h.withDO(h.DO.Offset(offset))
}

func (h hostEnvironmentDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IHostEnvironmentDo {
	return h.withDO(h.DO.Scopes(funcs...))
}

func (h hostEnvironmentDo) Unscoped() IHostEnvironmentDo {
	return h.withDO(h.DO.Unscoped())
}

func (h hostEnvironmentDo) Create(values ...*model.HostEnvironment) error {
	if len(values) == 0 {
		return nil
	}
	return h.DO.Create(values)
}

func (h hostEnvironmentDo) CreateInBatches(values []*model.HostEnvironment, batchSize int) error {
	return h.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (h hostEnvironmentDo) Save(values ...*model.HostEnvironment) error {
	if len(values) == 0 {
		return nil
	}
	return h.DO.Save(values)
}

func (h hostEnvironmentDo) First() (*model.HostEnvironment, error) {
	if result, err := h.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.HostEnvironment), nil
	}
}

func (h hostEnvironmentDo) Take() (*model.HostEnvironment, error) {
	if result, err := h.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.HostEnvironment), nil
	}
}

func (h hostEnvironmentDo) Last() (*model.HostEnvironment, error) {
	if result, err := h.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.HostEnvironment), nil
	}
}

func (h hostEnvironmentDo) Find() ([]*model.HostEnvironment, error) {
	result, err := h.DO.Find()
	return result.([]*model.HostEnvironment), err
}

func (h hostEnvironmentDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.HostEnvironment, err error) {
	buf := make([]*model.HostEnvironment, 0, batchSize)
	err = h.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (h hostEnvironmentDo) FindInBatches(result *[]*model.HostEnvironment, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return h.DO.FindInBatches(result, batchSize, fc)
}

func (h hostEnvironmentDo) Attrs(attrs ...field.AssignExpr) IHostEnvironmentDo {
	return h.withDO(h.DO.Attrs(attrs...))
}

func (h hostEnvironmentDo) Assign(attrs ...field.AssignExpr) IHostEnvironmentDo {
	return h.withDO(h.DO.Assign(attrs...))
}

func (h hostEnvironmentDo) Joins(fields ...field.RelationField) IHostEnvironmentDo {
	for _, _f := range fields {
		h = *h.withDO(h.DO.Joins(_f))
	}
	return &h
}

func (h hostEnvironmentDo) Preload(fields ...field.RelationField) IHostEnvironmentDo {
	for _, _f := range fields {
		h = *h.withDO(h.DO.Preload(_f))
	}
	return &h
}

func (h hostEnvironmentDo) FirstOrInit() (*model.HostEnvironment, error) {
	if result, err := h.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.HostEnvironment), nil
	}
}

func (h hostEnvironmentDo) FirstOrCreate() (*model.HostEnvironment, error) {
	if result, err := h.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.HostEnvironment), nil
	}
}

func (h hostEnvironmentDo) FindByPage(offset int, limit int) (result []*model.HostEnvironment, count int64, err error) {
	result, err = h.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = h.Offset(-1).Limit(-1).Count()
	return
}

func (h hostEnvironmentDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = h.Count()
	if err != nil {
		return
	}

	err = h.Offset(offset).Limit(limit).Scan(result)
	return
}

func (h hostEnvironmentDo) Scan(result interface{}) (err error) {
	return h.DO.Scan(result)
}

func (h hostEnvironmentDo) Delete(models ...*model.HostEnvironment) (result gen.ResultInfo, err error) {
	return h.DO.Delete(models)
}

func (h *hostEnvironmentDo) withDO(do gen.Dao) *hostEnvironmentDo {
	h.DO = *do.(*gen.DO)
	return h
}
