// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"irms/backend/internal/model"
)

func newHostCredential(db *gorm.DB, opts ...gen.DOOption) hostCredential {
	_hostCredential := hostCredential{}

	_hostCredential.hostCredentialDo.UseDB(db, opts...)
	_hostCredential.hostCredentialDo.UseModel(&model.HostCredential{})

	tableName := _hostCredential.hostCredentialDo.TableName()
	_hostCredential.ALL = field.NewAsterisk(tableName)
	_hostCredential.ID = field.NewUint64(tableName, "id")
	_hostCredential.HostID = field.NewUint64(tableName, "host_id")
	_hostCredential.AccountName = field.NewString(tableName, "account_name")
	_hostCredential.CredentialName = field.NewString(tableName, "credential_name")
	_hostCredential.CredentialKind = field.NewString(tableName, "credential_kind")
	_hostCredential.Username = field.NewString(tableName, "username")
	_hostCredential.SecretCiphertext = field.NewString(tableName, "secret_ciphertext")
	_hostCredential.CertificatePemCiphertext = field.NewString(tableName, "certificate_pem_ciphertext")
	_hostCredential.PrivateKeyPemCiphertext = field.NewString(tableName, "private_key_pem_ciphertext")
	_hostCredential.PassphraseCiphertext = field.NewString(tableName, "passphrase_ciphertext")
	_hostCredential.Status = field.NewString(tableName, "status")
	_hostCredential.Description = field.NewString(tableName, "description")
	_hostCredential.CreatedAt = field.NewTime(tableName, "created_at")
	_hostCredential.UpdatedAt = field.NewTime(tableName, "updated_at")

	_hostCredential.fillFieldMap()

	return _hostCredential
}

type hostCredential struct {
	hostCredentialDo hostCredentialDo

	ALL                      field.Asterisk
	ID                       field.Uint64
	HostID                   field.Uint64
	AccountName              field.String
	CredentialName           field.String
	CredentialKind           field.String
	Username                 field.String
	SecretCiphertext         field.String
	CertificatePemCiphertext field.String
	PrivateKeyPemCiphertext  field.String
	PassphraseCiphertext     field.String
	Status                   field.String
	Description              field.String
	CreatedAt                field.Time
	UpdatedAt                field.Time

	fieldMap map[string]field.Expr
}

func (h hostCredential) Table(newTableName string) *hostCredential {
	h.hostCredentialDo.UseTable(newTableName)
	return h.updateTableName(newTableName)
}

func (h hostCredential) As(alias string) *hostCredential {
	h.hostCredentialDo.DO = *(h.hostCredentialDo.As(alias).(*gen.DO))
	return h.updateTableName(alias)
}

func (h *hostCredential) updateTableName(table string) *hostCredential {
	h.ALL = field.NewAsterisk(table)
	h.ID = field.NewUint64(table, "id")
	h.HostID = field.NewUint64(table, "host_id")
	h.AccountName = field.NewString(table, "account_name")
	h.CredentialName = field.NewString(table, "credential_name")
	h.CredentialKind = field.NewString(table, "credential_kind")
	h.Username = field.NewString(table, "username")
	h.SecretCiphertext = field.NewString(table, "secret_ciphertext")
	h.CertificatePemCiphertext = field.NewString(table, "certificate_pem_ciphertext")
	h.PrivateKeyPemCiphertext = field.NewString(table, "private_key_pem_ciphertext")
	h.PassphraseCiphertext = field.NewString(table, "passphrase_ciphertext")
	h.Status = field.NewString(table, "status")
	h.Description = field.NewString(table, "description")
	h.CreatedAt = field.NewTime(table, "created_at")
	h.UpdatedAt = field.NewTime(table, "updated_at")

	h.fillFieldMap()

	return h
}

func (h *hostCredential) WithContext(ctx context.Context) IHostCredentialDo {
	return h.hostCredentialDo.WithContext(ctx)
}

func (h hostCredential) TableName() string { return h.hostCredentialDo.TableName() }

func (h hostCredential) Alias() string { return h.hostCredentialDo.Alias() }

func (h hostCredential) Columns(cols ...field.Expr) gen.Columns {
	return h.hostCredentialDo.Columns(cols...)
}

func (h *hostCredential) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := h.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (h *hostCredential) fillFieldMap() {
	h.fieldMap = make(map[string]field.Expr, 14)
	h.fieldMap["id"] = h.ID
	h.fieldMap["host_id"] = h.HostID
	h.fieldMap["account_name"] = h.AccountName
	h.fieldMap["credential_name"] = h.CredentialName
	h.fieldMap["credential_kind"] = h.CredentialKind
	h.fieldMap["username"] = h.Username
	h.fieldMap["secret_ciphertext"] = h.SecretCiphertext
	h.fieldMap["certificate_pem_ciphertext"] = h.CertificatePemCiphertext
	h.fieldMap["private_key_pem_ciphertext"] = h.PrivateKeyPemCiphertext
	h.fieldMap["passphrase_ciphertext"] = h.PassphraseCiphertext
	h.fieldMap["status"] = h.Status
	h.fieldMap["description"] = h.Description
	h.fieldMap["created_at"] = h.CreatedAt
	h.fieldMap["updated_at"] = h.UpdatedAt
}

func (h hostCredential) clone(db *gorm.DB) hostCredential {
	h.hostCredentialDo.ReplaceConnPool(db.Statement.ConnPool)
	return h
}

func (h hostCredential) replaceDB(db *gorm.DB) hostCredential {
	h.hostCredentialDo.ReplaceDB(db)
	return h
}

type hostCredentialDo struct{ gen.DO }

type IHostCredentialDo interface {
	gen.SubQuery
	Debug() IHostCredentialDo
	WithContext(ctx context.Context) IHostCredentialDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IHostCredentialDo
	WriteDB() IHostCredentialDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IHostCredentialDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IHostCredentialDo
	Not(conds ...gen.Condition) IHostCredentialDo
	Or(conds ...gen.Condition) IHostCredentialDo
	Select(conds ...field.Expr) IHostCredentialDo
	Where(conds ...gen.Condition) IHostCredentialDo
	Order(conds ...field.Expr) IHostCredentialDo
	Distinct(cols ...field.Expr) IHostCredentialDo
	Omit(cols ...field.Expr) IHostCredentialDo
	Join(table schema.Tabler, on ...field.Expr) IHostCredentialDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IHostCredentialDo
	RightJoin(table schema.Tabler, on ...field.Expr) IHostCredentialDo
	Group(cols ...field.Expr) IHostCredentialDo
	Having(conds ...gen.Condition) IHostCredentialDo
	Limit(limit int) IHostCredentialDo
	Offset(offset int) IHostCredentialDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IHostCredentialDo
	Unscoped() IHostCredentialDo
	Create(values ...*model.HostCredential) error
	CreateInBatches(values []*model.HostCredential, batchSize int) error
	Save(values ...*model.HostCredential) error
	First() (*model.HostCredential, error)
	Take() (*model.HostCredential, error)
	Last() (*model.HostCredential, error)
	Find() ([]*model.HostCredential, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.HostCredential, err error)
	FindInBatches(result *[]*model.HostCredential, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.HostCredential) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IHostCredentialDo
	Assign(attrs ...field.AssignExpr) IHostCredentialDo
	Joins(fields ...field.RelationField) IHostCredentialDo
	Preload(fields ...field.RelationField) IHostCredentialDo
	FirstOrInit() (*model.HostCredential, error)
	FirstOrCreate() (*model.HostCredential, error)
	FindByPage(offset int, limit int) (result []*model.HostCredential, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IHostCredentialDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (h hostCredentialDo) Debug() IHostCredentialDo {
	return h.withDO(h.DO.Debug())
}

func (h hostCredentialDo) WithContext(ctx context.Context) IHostCredentialDo {
	return h.withDO(h.DO.WithContext(ctx))
}

func (h hostCredentialDo) ReadDB() IHostCredentialDo {
	return h.Clauses(dbresolver.Read)
}

func (h hostCredentialDo) WriteDB() IHostCredentialDo {
	return h.Clauses(dbresolver.Write)
}

func (h hostCredentialDo) Session(config *gorm.Session) IHostCredentialDo {
	return h.withDO(h.DO.Session(config))
}

func (h hostCredentialDo) Clauses(conds ...clause.Expression) IHostCredentialDo {
	return h.withDO(h.DO.Clauses(conds...))
}

func (h hostCredentialDo) Returning(value interface{}, columns ...string) IHostCredentialDo {
	return h.withDO(h.DO.Returning(value, columns...))
}

func (h hostCredentialDo) Not(conds ...gen.Condition) IHostCredentialDo {
	return h.withDO(h.DO.Not(conds...))
}

func (h hostCredentialDo) Or(conds ...gen.Condition) IHostCredentialDo {
	return h.withDO(h.DO.Or(conds...))
}

func (h hostCredentialDo) Select(conds ...field.Expr) IHostCredentialDo {
	return h.withDO(h.DO.Select(conds...))
}

func (h hostCredentialDo) Where(conds ...gen.Condition) IHostCredentialDo {
	return h.withDO(h.DO.Where(conds...))
}

func (h hostCredentialDo) Order(conds ...field.Expr) IHostCredentialDo {
	return h.withDO(h.DO.Order(conds...))
}

func (h hostCredentialDo) Distinct(cols ...field.Expr) IHostCredentialDo {
	return h.withDO(h.DO.Distinct(cols...))
}

func (h hostCredentialDo) Omit(cols ...field.Expr) IHostCredentialDo {
	return h.withDO(h.DO.Omit(cols...))
}

func (h hostCredentialDo) Join(table schema.Tabler, on ...field.Expr) IHostCredentialDo {
	return h.withDO(h.DO.Join(table, on...))
}

func (h hostCredentialDo) LeftJoin(table schema.Tabler, on ...field.Expr) IHostCredentialDo {
	return h.withDO(h.DO.LeftJoin(table, on...))
}

func (h hostCredentialDo) RightJoin(table schema.Tabler, on ...field.Expr) IHostCredentialDo {
	return h.withDO(h.DO.RightJoin(table, on...))
}

func (h hostCredentialDo) Group(cols ...field.Expr) IHostCredentialDo {
	return h.withDO(h.DO.Group(cols...))
}

func (h hostCredentialDo) Having(conds ...gen.Condition) IHostCredentialDo {
	return h.withDO(h.DO.Having(conds...))
}

func (h hostCredentialDo) Limit(limit int) IHostCredentialDo {
	return h.withDO(h.DO.Limit(limit))
}

func (h hostCredentialDo) Offset(offset int) IHostCredentialDo {
	return h.withDO(h.DO.Offset(offset))
}

func (h hostCredentialDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IHostCredentialDo {
	return h.withDO(h.DO.Scopes(funcs...))
}

func (h hostCredentialDo) Unscoped() IHostCredentialDo {
	return h.withDO(h.DO.Unscoped())
}

func (h hostCredentialDo) Create(values ...*model.HostCredential) error {
	if len(values) == 0 {
		return nil
	}
	return h.DO.Create(values)
}

func (h hostCredentialDo) CreateInBatches(values []*model.HostCredential, batchSize int) error {
	return h.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (h hostCredentialDo) Save(values ...*model.HostCredential) error {
	if len(values) == 0 {
		return nil
	}
	return h.DO.Save(values)
}

func (h hostCredentialDo) First() (*model.HostCredential, error) {
	if result, err := h.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.HostCredential), nil
	}
}

func (h hostCredentialDo) Take() (*model.HostCredential, error) {
	if result, err := h.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.HostCredential), nil
	}
}

func (h hostCredentialDo) Last() (*model.HostCredential, error) {
	if result, err := h.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.HostCredential), nil
	}
}

func (h hostCredentialDo) Find() ([]*model.HostCredential, error) {
	result, err := h.DO.Find()
	return result.([]*model.HostCredential), err
}

func (h hostCredentialDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.HostCredential, err error) {
	buf := make([]*model.HostCredential, 0, batchSize)
	err = h.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (h hostCredentialDo) FindInBatches(result *[]*model.HostCredential, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return h.DO.FindInBatches(result, batchSize, fc)
}

func (h hostCredentialDo) Attrs(attrs ...field.AssignExpr) IHostCredentialDo {
	return h.withDO(h.DO.Attrs(attrs...))
}

func (h hostCredentialDo) Assign(attrs ...field.AssignExpr) IHostCredentialDo {
	return h.withDO(h.DO.Assign(attrs...))
}

func (h hostCredentialDo) Joins(fields ...field.RelationField) IHostCredentialDo {
	for _, _f := range fields {
		h = *h.withDO(h.DO.Joins(_f))
	}
	return &h
}

func (h hostCredentialDo) Preload(fields ...field.RelationField) IHostCredentialDo {
	for _, _f := range fields {
		h = *h.withDO(h.DO.Preload(_f))
	}
	return &h
}

func (h hostCredentialDo) FirstOrInit() (*model.HostCredential, error) {
	if result, err := h.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.HostCredential), nil
	}
}

func (h hostCredentialDo) FirstOrCreate() (*model.HostCredential, error) {
	if result, err := h.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.HostCredential), nil
	}
}

func (h hostCredentialDo) FindByPage(offset int, limit int) (result []*model.HostCredential, count int64, err error) {
	result, err = h.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = h.Offset(-1).Limit(-1).Count()
	return
}

func (h hostCredentialDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = h.Count()
	if err != nil {
		return
	}

	err = h.Offset(offset).Limit(limit).Scan(result)
	return
}

func (h hostCredentialDo) Scan(result interface{}) (err error) {
	return h.DO.Scan(result)
}

func (h hostCredentialDo) Delete(models ...*model.HostCredential) (result gen.ResultInfo, err error) {
	return h.DO.Delete(models)
}

func (h *hostCredentialDo) withDO(do gen.Dao) *hostCredentialDo {
	h.DO = *do.(*gen.DO)
	return h
}
