// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"irms/backend/internal/model"
)

func newPermissionDefinition(db *gorm.DB, opts ...gen.DOOption) permissionDefinition {
	_permissionDefinition := permissionDefinition{}

	_permissionDefinition.permissionDefinitionDo.UseDB(db, opts...)
	_permissionDefinition.permissionDefinitionDo.UseModel(&model.PermissionDefinition{})

	tableName := _permissionDefinition.permissionDefinitionDo.TableName()
	_permissionDefinition.ALL = field.NewAsterisk(tableName)
	_permissionDefinition.ID = field.NewUint64(tableName, "id")
	_permissionDefinition.Code = field.NewString(tableName, "code")
	_permissionDefinition.ObjectFamily = field.NewString(tableName, "object_family")
	_permissionDefinition.Action = field.NewString(tableName, "action")
	_permissionDefinition.DisplayName = field.NewString(tableName, "display_name")
	_permissionDefinition.Description = field.NewString(tableName, "description")
	_permissionDefinition.Status = field.NewString(tableName, "status")
	_permissionDefinition.CreatedAt = field.NewTime(tableName, "created_at")
	_permissionDefinition.UpdatedAt = field.NewTime(tableName, "updated_at")

	_permissionDefinition.fillFieldMap()

	return _permissionDefinition
}

type permissionDefinition struct {
	permissionDefinitionDo permissionDefinitionDo

	ALL          field.Asterisk
	ID           field.Uint64
	Code         field.String
	ObjectFamily field.String
	Action       field.String
	DisplayName  field.String
	Description  field.String
	Status       field.String
	CreatedAt    field.Time
	UpdatedAt    field.Time

	fieldMap map[string]field.Expr
}

func (p permissionDefinition) Table(newTableName string) *permissionDefinition {
	p.permissionDefinitionDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p permissionDefinition) As(alias string) *permissionDefinition {
	p.permissionDefinitionDo.DO = *(p.permissionDefinitionDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *permissionDefinition) updateTableName(table string) *permissionDefinition {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewUint64(table, "id")
	p.Code = field.NewString(table, "code")
	p.ObjectFamily = field.NewString(table, "object_family")
	p.Action = field.NewString(table, "action")
	p.DisplayName = field.NewString(table, "display_name")
	p.Description = field.NewString(table, "description")
	p.Status = field.NewString(table, "status")
	p.CreatedAt = field.NewTime(table, "created_at")
	p.UpdatedAt = field.NewTime(table, "updated_at")

	p.fillFieldMap()

	return p
}

func (p *permissionDefinition) WithContext(ctx context.Context) IPermissionDefinitionDo {
	return p.permissionDefinitionDo.WithContext(ctx)
}

func (p permissionDefinition) TableName() string { return p.permissionDefinitionDo.TableName() }

func (p permissionDefinition) Alias() string { return p.permissionDefinitionDo.Alias() }

func (p permissionDefinition) Columns(cols ...field.Expr) gen.Columns {
	return p.permissionDefinitionDo.Columns(cols...)
}

func (p *permissionDefinition) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *permissionDefinition) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 9)
	p.fieldMap["id"] = p.ID
	p.fieldMap["code"] = p.Code
	p.fieldMap["object_family"] = p.ObjectFamily
	p.fieldMap["action"] = p.Action
	p.fieldMap["display_name"] = p.DisplayName
	p.fieldMap["description"] = p.Description
	p.fieldMap["status"] = p.Status
	p.fieldMap["created_at"] = p.CreatedAt
	p.fieldMap["updated_at"] = p.UpdatedAt
}

func (p permissionDefinition) clone(db *gorm.DB) permissionDefinition {
	p.permissionDefinitionDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p permissionDefinition) replaceDB(db *gorm.DB) permissionDefinition {
	p.permissionDefinitionDo.ReplaceDB(db)
	return p
}

type permissionDefinitionDo struct{ gen.DO }

type IPermissionDefinitionDo interface {
	gen.SubQuery
	Debug() IPermissionDefinitionDo
	WithContext(ctx context.Context) IPermissionDefinitionDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IPermissionDefinitionDo
	WriteDB() IPermissionDefinitionDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IPermissionDefinitionDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IPermissionDefinitionDo
	Not(conds ...gen.Condition) IPermissionDefinitionDo
	Or(conds ...gen.Condition) IPermissionDefinitionDo
	Select(conds ...field.Expr) IPermissionDefinitionDo
	Where(conds ...gen.Condition) IPermissionDefinitionDo
	Order(conds ...field.Expr) IPermissionDefinitionDo
	Distinct(cols ...field.Expr) IPermissionDefinitionDo
	Omit(cols ...field.Expr) IPermissionDefinitionDo
	Join(table schema.Tabler, on ...field.Expr) IPermissionDefinitionDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IPermissionDefinitionDo
	RightJoin(table schema.Tabler, on ...field.Expr) IPermissionDefinitionDo
	Group(cols ...field.Expr) IPermissionDefinitionDo
	Having(conds ...gen.Condition) IPermissionDefinitionDo
	Limit(limit int) IPermissionDefinitionDo
	Offset(offset int) IPermissionDefinitionDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IPermissionDefinitionDo
	Unscoped() IPermissionDefinitionDo
	Create(values ...*model.PermissionDefinition) error
	CreateInBatches(values []*model.PermissionDefinition, batchSize int) error
	Save(values ...*model.PermissionDefinition) error
	First() (*model.PermissionDefinition, error)
	Take() (*model.PermissionDefinition, error)
	Last() (*model.PermissionDefinition, error)
	Find() ([]*model.PermissionDefinition, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PermissionDefinition, err error)
	FindInBatches(result *[]*model.PermissionDefinition, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.PermissionDefinition) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IPermissionDefinitionDo
	Assign(attrs ...field.AssignExpr) IPermissionDefinitionDo
	Joins(fields ...field.RelationField) IPermissionDefinitionDo
	Preload(fields ...field.RelationField) IPermissionDefinitionDo
	FirstOrInit() (*model.PermissionDefinition, error)
	FirstOrCreate() (*model.PermissionDefinition, error)
	FindByPage(offset int, limit int) (result []*model.PermissionDefinition, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IPermissionDefinitionDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p permissionDefinitionDo) Debug() IPermissionDefinitionDo {
	return p.withDO(p.DO.Debug())
}

func (p permissionDefinitionDo) WithContext(ctx context.Context) IPermissionDefinitionDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p permissionDefinitionDo) ReadDB() IPermissionDefinitionDo {
	return p.Clauses(dbresolver.Read)
}

func (p permissionDefinitionDo) WriteDB() IPermissionDefinitionDo {
	return p.Clauses(dbresolver.Write)
}

func (p permissionDefinitionDo) Session(config *gorm.Session) IPermissionDefinitionDo {
	return p.withDO(p.DO.Session(config))
}

func (p permissionDefinitionDo) Clauses(conds ...clause.Expression) IPermissionDefinitionDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p permissionDefinitionDo) Returning(value interface{}, columns ...string) IPermissionDefinitionDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p permissionDefinitionDo) Not(conds ...gen.Condition) IPermissionDefinitionDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p permissionDefinitionDo) Or(conds ...gen.Condition) IPermissionDefinitionDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p permissionDefinitionDo) Select(conds ...field.Expr) IPermissionDefinitionDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p permissionDefinitionDo) Where(conds ...gen.Condition) IPermissionDefinitionDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p permissionDefinitionDo) Order(conds ...field.Expr) IPermissionDefinitionDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p permissionDefinitionDo) Distinct(cols ...field.Expr) IPermissionDefinitionDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p permissionDefinitionDo) Omit(cols ...field.Expr) IPermissionDefinitionDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p permissionDefinitionDo) Join(table schema.Tabler, on ...field.Expr) IPermissionDefinitionDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p permissionDefinitionDo) LeftJoin(table schema.Tabler, on ...field.Expr) IPermissionDefinitionDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p permissionDefinitionDo) RightJoin(table schema.Tabler, on ...field.Expr) IPermissionDefinitionDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p permissionDefinitionDo) Group(cols ...field.Expr) IPermissionDefinitionDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p permissionDefinitionDo) Having(conds ...gen.Condition) IPermissionDefinitionDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p permissionDefinitionDo) Limit(limit int) IPermissionDefinitionDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p permissionDefinitionDo) Offset(offset int) IPermissionDefinitionDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p permissionDefinitionDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IPermissionDefinitionDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p permissionDefinitionDo) Unscoped() IPermissionDefinitionDo {
	return p.withDO(p.DO.Unscoped())
}

func (p permissionDefinitionDo) Create(values ...*model.PermissionDefinition) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p permissionDefinitionDo) CreateInBatches(values []*model.PermissionDefinition, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p permissionDefinitionDo) Save(values ...*model.PermissionDefinition) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p permissionDefinitionDo) First() (*model.PermissionDefinition, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.PermissionDefinition), nil
	}
}

func (p permissionDefinitionDo) Take() (*model.PermissionDefinition, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.PermissionDefinition), nil
	}
}

func (p permissionDefinitionDo) Last() (*model.PermissionDefinition, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.PermissionDefinition), nil
	}
}

func (p permissionDefinitionDo) Find() ([]*model.PermissionDefinition, error) {
	result, err := p.DO.Find()
	return result.([]*model.PermissionDefinition), err
}

func (p permissionDefinitionDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PermissionDefinition, err error) {
	buf := make([]*model.PermissionDefinition, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p permissionDefinitionDo) FindInBatches(result *[]*model.PermissionDefinition, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p permissionDefinitionDo) Attrs(attrs ...field.AssignExpr) IPermissionDefinitionDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p permissionDefinitionDo) Assign(attrs ...field.AssignExpr) IPermissionDefinitionDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p permissionDefinitionDo) Joins(fields ...field.RelationField) IPermissionDefinitionDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p permissionDefinitionDo) Preload(fields ...field.RelationField) IPermissionDefinitionDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p permissionDefinitionDo) FirstOrInit() (*model.PermissionDefinition, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.PermissionDefinition), nil
	}
}

func (p permissionDefinitionDo) FirstOrCreate() (*model.PermissionDefinition, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.PermissionDefinition), nil
	}
}

func (p permissionDefinitionDo) FindByPage(offset int, limit int) (result []*model.PermissionDefinition, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p permissionDefinitionDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p permissionDefinitionDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p permissionDefinitionDo) Delete(models ...*model.PermissionDefinition) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *permissionDefinitionDo) withDO(do gen.Dao) *permissionDefinitionDo {
	p.DO = *do.(*gen.DO)
	return p
}
