// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"irms/backend/internal/model"
)

func newResourceGroupMember(db *gorm.DB, opts ...gen.DOOption) resourceGroupMember {
	_resourceGroupMember := resourceGroupMember{}

	_resourceGroupMember.resourceGroupMemberDo.UseDB(db, opts...)
	_resourceGroupMember.resourceGroupMemberDo.UseModel(&model.ResourceGroupMember{})

	tableName := _resourceGroupMember.resourceGroupMemberDo.TableName()
	_resourceGroupMember.ALL = field.NewAsterisk(tableName)
	_resourceGroupMember.ID = field.NewUint64(tableName, "id")
	_resourceGroupMember.ResourceKey = field.NewUint64(tableName, "resource_key")
	_resourceGroupMember.ResourceGroupID = field.NewUint64(tableName, "resource_group_id")
	_resourceGroupMember.CreatedAt = field.NewTime(tableName, "created_at")

	_resourceGroupMember.fillFieldMap()

	return _resourceGroupMember
}

// resourceGroupMember compatibility storage: resource_group_members
type resourceGroupMember struct {
	resourceGroupMemberDo resourceGroupMemberDo

	ALL             field.Asterisk
	ID              field.Uint64
	ResourceKey     field.Uint64
	ResourceGroupID field.Uint64
	CreatedAt       field.Time

	fieldMap map[string]field.Expr
}

func (r resourceGroupMember) Table(newTableName string) *resourceGroupMember {
	r.resourceGroupMemberDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r resourceGroupMember) As(alias string) *resourceGroupMember {
	r.resourceGroupMemberDo.DO = *(r.resourceGroupMemberDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *resourceGroupMember) updateTableName(table string) *resourceGroupMember {
	r.ALL = field.NewAsterisk(table)
	r.ID = field.NewUint64(table, "id")
	r.ResourceKey = field.NewUint64(table, "resource_key")
	r.ResourceGroupID = field.NewUint64(table, "resource_group_id")
	r.CreatedAt = field.NewTime(table, "created_at")

	r.fillFieldMap()

	return r
}

func (r *resourceGroupMember) WithContext(ctx context.Context) IResourceGroupMemberDo {
	return r.resourceGroupMemberDo.WithContext(ctx)
}

func (r resourceGroupMember) TableName() string { return r.resourceGroupMemberDo.TableName() }

func (r resourceGroupMember) Alias() string { return r.resourceGroupMemberDo.Alias() }

func (r resourceGroupMember) Columns(cols ...field.Expr) gen.Columns {
	return r.resourceGroupMemberDo.Columns(cols...)
}

func (r *resourceGroupMember) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *resourceGroupMember) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 4)
	r.fieldMap["id"] = r.ID
	r.fieldMap["resource_key"] = r.ResourceKey
	r.fieldMap["resource_group_id"] = r.ResourceGroupID
	r.fieldMap["created_at"] = r.CreatedAt
}

func (r resourceGroupMember) clone(db *gorm.DB) resourceGroupMember {
	r.resourceGroupMemberDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r resourceGroupMember) replaceDB(db *gorm.DB) resourceGroupMember {
	r.resourceGroupMemberDo.ReplaceDB(db)
	return r
}

type resourceGroupMemberDo struct{ gen.DO }

type IResourceGroupMemberDo interface {
	gen.SubQuery
	Debug() IResourceGroupMemberDo
	WithContext(ctx context.Context) IResourceGroupMemberDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IResourceGroupMemberDo
	WriteDB() IResourceGroupMemberDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IResourceGroupMemberDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IResourceGroupMemberDo
	Not(conds ...gen.Condition) IResourceGroupMemberDo
	Or(conds ...gen.Condition) IResourceGroupMemberDo
	Select(conds ...field.Expr) IResourceGroupMemberDo
	Where(conds ...gen.Condition) IResourceGroupMemberDo
	Order(conds ...field.Expr) IResourceGroupMemberDo
	Distinct(cols ...field.Expr) IResourceGroupMemberDo
	Omit(cols ...field.Expr) IResourceGroupMemberDo
	Join(table schema.Tabler, on ...field.Expr) IResourceGroupMemberDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IResourceGroupMemberDo
	RightJoin(table schema.Tabler, on ...field.Expr) IResourceGroupMemberDo
	Group(cols ...field.Expr) IResourceGroupMemberDo
	Having(conds ...gen.Condition) IResourceGroupMemberDo
	Limit(limit int) IResourceGroupMemberDo
	Offset(offset int) IResourceGroupMemberDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IResourceGroupMemberDo
	Unscoped() IResourceGroupMemberDo
	Create(values ...*model.ResourceGroupMember) error
	CreateInBatches(values []*model.ResourceGroupMember, batchSize int) error
	Save(values ...*model.ResourceGroupMember) error
	First() (*model.ResourceGroupMember, error)
	Take() (*model.ResourceGroupMember, error)
	Last() (*model.ResourceGroupMember, error)
	Find() ([]*model.ResourceGroupMember, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ResourceGroupMember, err error)
	FindInBatches(result *[]*model.ResourceGroupMember, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.ResourceGroupMember) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IResourceGroupMemberDo
	Assign(attrs ...field.AssignExpr) IResourceGroupMemberDo
	Joins(fields ...field.RelationField) IResourceGroupMemberDo
	Preload(fields ...field.RelationField) IResourceGroupMemberDo
	FirstOrInit() (*model.ResourceGroupMember, error)
	FirstOrCreate() (*model.ResourceGroupMember, error)
	FindByPage(offset int, limit int) (result []*model.ResourceGroupMember, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IResourceGroupMemberDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (r resourceGroupMemberDo) Debug() IResourceGroupMemberDo {
	return r.withDO(r.DO.Debug())
}

func (r resourceGroupMemberDo) WithContext(ctx context.Context) IResourceGroupMemberDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r resourceGroupMemberDo) ReadDB() IResourceGroupMemberDo {
	return r.Clauses(dbresolver.Read)
}

func (r resourceGroupMemberDo) WriteDB() IResourceGroupMemberDo {
	return r.Clauses(dbresolver.Write)
}

func (r resourceGroupMemberDo) Session(config *gorm.Session) IResourceGroupMemberDo {
	return r.withDO(r.DO.Session(config))
}

func (r resourceGroupMemberDo) Clauses(conds ...clause.Expression) IResourceGroupMemberDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r resourceGroupMemberDo) Returning(value interface{}, columns ...string) IResourceGroupMemberDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r resourceGroupMemberDo) Not(conds ...gen.Condition) IResourceGroupMemberDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r resourceGroupMemberDo) Or(conds ...gen.Condition) IResourceGroupMemberDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r resourceGroupMemberDo) Select(conds ...field.Expr) IResourceGroupMemberDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r resourceGroupMemberDo) Where(conds ...gen.Condition) IResourceGroupMemberDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r resourceGroupMemberDo) Order(conds ...field.Expr) IResourceGroupMemberDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r resourceGroupMemberDo) Distinct(cols ...field.Expr) IResourceGroupMemberDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r resourceGroupMemberDo) Omit(cols ...field.Expr) IResourceGroupMemberDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r resourceGroupMemberDo) Join(table schema.Tabler, on ...field.Expr) IResourceGroupMemberDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r resourceGroupMemberDo) LeftJoin(table schema.Tabler, on ...field.Expr) IResourceGroupMemberDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r resourceGroupMemberDo) RightJoin(table schema.Tabler, on ...field.Expr) IResourceGroupMemberDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r resourceGroupMemberDo) Group(cols ...field.Expr) IResourceGroupMemberDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r resourceGroupMemberDo) Having(conds ...gen.Condition) IResourceGroupMemberDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r resourceGroupMemberDo) Limit(limit int) IResourceGroupMemberDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r resourceGroupMemberDo) Offset(offset int) IResourceGroupMemberDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r resourceGroupMemberDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IResourceGroupMemberDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r resourceGroupMemberDo) Unscoped() IResourceGroupMemberDo {
	return r.withDO(r.DO.Unscoped())
}

func (r resourceGroupMemberDo) Create(values ...*model.ResourceGroupMember) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r resourceGroupMemberDo) CreateInBatches(values []*model.ResourceGroupMember, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r resourceGroupMemberDo) Save(values ...*model.ResourceGroupMember) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r resourceGroupMemberDo) First() (*model.ResourceGroupMember, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ResourceGroupMember), nil
	}
}

func (r resourceGroupMemberDo) Take() (*model.ResourceGroupMember, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ResourceGroupMember), nil
	}
}

func (r resourceGroupMemberDo) Last() (*model.ResourceGroupMember, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ResourceGroupMember), nil
	}
}

func (r resourceGroupMemberDo) Find() ([]*model.ResourceGroupMember, error) {
	result, err := r.DO.Find()
	return result.([]*model.ResourceGroupMember), err
}

func (r resourceGroupMemberDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ResourceGroupMember, err error) {
	buf := make([]*model.ResourceGroupMember, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r resourceGroupMemberDo) FindInBatches(result *[]*model.ResourceGroupMember, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r resourceGroupMemberDo) Attrs(attrs ...field.AssignExpr) IResourceGroupMemberDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r resourceGroupMemberDo) Assign(attrs ...field.AssignExpr) IResourceGroupMemberDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r resourceGroupMemberDo) Joins(fields ...field.RelationField) IResourceGroupMemberDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r resourceGroupMemberDo) Preload(fields ...field.RelationField) IResourceGroupMemberDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r resourceGroupMemberDo) FirstOrInit() (*model.ResourceGroupMember, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ResourceGroupMember), nil
	}
}

func (r resourceGroupMemberDo) FirstOrCreate() (*model.ResourceGroupMember, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ResourceGroupMember), nil
	}
}

func (r resourceGroupMemberDo) FindByPage(offset int, limit int) (result []*model.ResourceGroupMember, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r resourceGroupMemberDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r resourceGroupMemberDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r resourceGroupMemberDo) Delete(models ...*model.ResourceGroupMember) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *resourceGroupMemberDo) withDO(do gen.Dao) *resourceGroupMemberDo {
	r.DO = *do.(*gen.DO)
	return r
}
