// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"irms/backend/internal/model"
)

func newResourceGroup(db *gorm.DB, opts ...gen.DOOption) resourceGroup {
	_resourceGroup := resourceGroup{}

	_resourceGroup.resourceGroupDo.UseDB(db, opts...)
	_resourceGroup.resourceGroupDo.UseModel(&model.ResourceGroup{})

	tableName := _resourceGroup.resourceGroupDo.TableName()
	_resourceGroup.ALL = field.NewAsterisk(tableName)
	_resourceGroup.ID = field.NewUint64(tableName, "id")
	_resourceGroup.Name = field.NewString(tableName, "name")
	_resourceGroup.Type = field.NewString(tableName, "type")
	_resourceGroup.Description = field.NewString(tableName, "description")
	_resourceGroup.CreatedAt = field.NewTime(tableName, "created_at")
	_resourceGroup.UpdatedAt = field.NewTime(tableName, "updated_at")

	_resourceGroup.fillFieldMap()

	return _resourceGroup
}

// resourceGroup compatibility storage: resource_groups
type resourceGroup struct {
	resourceGroupDo resourceGroupDo

	ALL         field.Asterisk
	ID          field.Uint64
	Name        field.String
	Type        field.String
	Description field.String
	CreatedAt   field.Time
	UpdatedAt   field.Time

	fieldMap map[string]field.Expr
}

func (r resourceGroup) Table(newTableName string) *resourceGroup {
	r.resourceGroupDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r resourceGroup) As(alias string) *resourceGroup {
	r.resourceGroupDo.DO = *(r.resourceGroupDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *resourceGroup) updateTableName(table string) *resourceGroup {
	r.ALL = field.NewAsterisk(table)
	r.ID = field.NewUint64(table, "id")
	r.Name = field.NewString(table, "name")
	r.Type = field.NewString(table, "type")
	r.Description = field.NewString(table, "description")
	r.CreatedAt = field.NewTime(table, "created_at")
	r.UpdatedAt = field.NewTime(table, "updated_at")

	r.fillFieldMap()

	return r
}

func (r *resourceGroup) WithContext(ctx context.Context) IResourceGroupDo {
	return r.resourceGroupDo.WithContext(ctx)
}

func (r resourceGroup) TableName() string { return r.resourceGroupDo.TableName() }

func (r resourceGroup) Alias() string { return r.resourceGroupDo.Alias() }

func (r resourceGroup) Columns(cols ...field.Expr) gen.Columns {
	return r.resourceGroupDo.Columns(cols...)
}

func (r *resourceGroup) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *resourceGroup) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 6)
	r.fieldMap["id"] = r.ID
	r.fieldMap["name"] = r.Name
	r.fieldMap["type"] = r.Type
	r.fieldMap["description"] = r.Description
	r.fieldMap["created_at"] = r.CreatedAt
	r.fieldMap["updated_at"] = r.UpdatedAt
}

func (r resourceGroup) clone(db *gorm.DB) resourceGroup {
	r.resourceGroupDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r resourceGroup) replaceDB(db *gorm.DB) resourceGroup {
	r.resourceGroupDo.ReplaceDB(db)
	return r
}

type resourceGroupDo struct{ gen.DO }

type IResourceGroupDo interface {
	gen.SubQuery
	Debug() IResourceGroupDo
	WithContext(ctx context.Context) IResourceGroupDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IResourceGroupDo
	WriteDB() IResourceGroupDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IResourceGroupDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IResourceGroupDo
	Not(conds ...gen.Condition) IResourceGroupDo
	Or(conds ...gen.Condition) IResourceGroupDo
	Select(conds ...field.Expr) IResourceGroupDo
	Where(conds ...gen.Condition) IResourceGroupDo
	Order(conds ...field.Expr) IResourceGroupDo
	Distinct(cols ...field.Expr) IResourceGroupDo
	Omit(cols ...field.Expr) IResourceGroupDo
	Join(table schema.Tabler, on ...field.Expr) IResourceGroupDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IResourceGroupDo
	RightJoin(table schema.Tabler, on ...field.Expr) IResourceGroupDo
	Group(cols ...field.Expr) IResourceGroupDo
	Having(conds ...gen.Condition) IResourceGroupDo
	Limit(limit int) IResourceGroupDo
	Offset(offset int) IResourceGroupDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IResourceGroupDo
	Unscoped() IResourceGroupDo
	Create(values ...*model.ResourceGroup) error
	CreateInBatches(values []*model.ResourceGroup, batchSize int) error
	Save(values ...*model.ResourceGroup) error
	First() (*model.ResourceGroup, error)
	Take() (*model.ResourceGroup, error)
	Last() (*model.ResourceGroup, error)
	Find() ([]*model.ResourceGroup, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ResourceGroup, err error)
	FindInBatches(result *[]*model.ResourceGroup, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.ResourceGroup) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IResourceGroupDo
	Assign(attrs ...field.AssignExpr) IResourceGroupDo
	Joins(fields ...field.RelationField) IResourceGroupDo
	Preload(fields ...field.RelationField) IResourceGroupDo
	FirstOrInit() (*model.ResourceGroup, error)
	FirstOrCreate() (*model.ResourceGroup, error)
	FindByPage(offset int, limit int) (result []*model.ResourceGroup, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IResourceGroupDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (r resourceGroupDo) Debug() IResourceGroupDo {
	return r.withDO(r.DO.Debug())
}

func (r resourceGroupDo) WithContext(ctx context.Context) IResourceGroupDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r resourceGroupDo) ReadDB() IResourceGroupDo {
	return r.Clauses(dbresolver.Read)
}

func (r resourceGroupDo) WriteDB() IResourceGroupDo {
	return r.Clauses(dbresolver.Write)
}

func (r resourceGroupDo) Session(config *gorm.Session) IResourceGroupDo {
	return r.withDO(r.DO.Session(config))
}

func (r resourceGroupDo) Clauses(conds ...clause.Expression) IResourceGroupDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r resourceGroupDo) Returning(value interface{}, columns ...string) IResourceGroupDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r resourceGroupDo) Not(conds ...gen.Condition) IResourceGroupDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r resourceGroupDo) Or(conds ...gen.Condition) IResourceGroupDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r resourceGroupDo) Select(conds ...field.Expr) IResourceGroupDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r resourceGroupDo) Where(conds ...gen.Condition) IResourceGroupDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r resourceGroupDo) Order(conds ...field.Expr) IResourceGroupDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r resourceGroupDo) Distinct(cols ...field.Expr) IResourceGroupDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r resourceGroupDo) Omit(cols ...field.Expr) IResourceGroupDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r resourceGroupDo) Join(table schema.Tabler, on ...field.Expr) IResourceGroupDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r resourceGroupDo) LeftJoin(table schema.Tabler, on ...field.Expr) IResourceGroupDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r resourceGroupDo) RightJoin(table schema.Tabler, on ...field.Expr) IResourceGroupDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r resourceGroupDo) Group(cols ...field.Expr) IResourceGroupDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r resourceGroupDo) Having(conds ...gen.Condition) IResourceGroupDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r resourceGroupDo) Limit(limit int) IResourceGroupDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r resourceGroupDo) Offset(offset int) IResourceGroupDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r resourceGroupDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IResourceGroupDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r resourceGroupDo) Unscoped() IResourceGroupDo {
	return r.withDO(r.DO.Unscoped())
}

func (r resourceGroupDo) Create(values ...*model.ResourceGroup) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r resourceGroupDo) CreateInBatches(values []*model.ResourceGroup, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r resourceGroupDo) Save(values ...*model.ResourceGroup) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r resourceGroupDo) First() (*model.ResourceGroup, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ResourceGroup), nil
	}
}

func (r resourceGroupDo) Take() (*model.ResourceGroup, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ResourceGroup), nil
	}
}

func (r resourceGroupDo) Last() (*model.ResourceGroup, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ResourceGroup), nil
	}
}

func (r resourceGroupDo) Find() ([]*model.ResourceGroup, error) {
	result, err := r.DO.Find()
	return result.([]*model.ResourceGroup), err
}

func (r resourceGroupDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ResourceGroup, err error) {
	buf := make([]*model.ResourceGroup, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r resourceGroupDo) FindInBatches(result *[]*model.ResourceGroup, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r resourceGroupDo) Attrs(attrs ...field.AssignExpr) IResourceGroupDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r resourceGroupDo) Assign(attrs ...field.AssignExpr) IResourceGroupDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r resourceGroupDo) Joins(fields ...field.RelationField) IResourceGroupDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r resourceGroupDo) Preload(fields ...field.RelationField) IResourceGroupDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r resourceGroupDo) FirstOrInit() (*model.ResourceGroup, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ResourceGroup), nil
	}
}

func (r resourceGroupDo) FirstOrCreate() (*model.ResourceGroup, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ResourceGroup), nil
	}
}

func (r resourceGroupDo) FindByPage(offset int, limit int) (result []*model.ResourceGroup, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r resourceGroupDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r resourceGroupDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r resourceGroupDo) Delete(models ...*model.ResourceGroup) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *resourceGroupDo) withDO(do gen.Dao) *resourceGroupDo {
	r.DO = *do.(*gen.DO)
	return r
}
