// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"irms/backend/internal/model"
)

func newServiceCredential(db *gorm.DB, opts ...gen.DOOption) serviceCredential {
	_serviceCredential := serviceCredential{}

	_serviceCredential.serviceCredentialDo.UseDB(db, opts...)
	_serviceCredential.serviceCredentialDo.UseModel(&model.ServiceCredential{})

	tableName := _serviceCredential.serviceCredentialDo.TableName()
	_serviceCredential.ALL = field.NewAsterisk(tableName)
	_serviceCredential.ID = field.NewUint64(tableName, "id")
	_serviceCredential.ServiceID = field.NewUint64(tableName, "service_id")
	_serviceCredential.AccountName = field.NewString(tableName, "account_name")
	_serviceCredential.CredentialName = field.NewString(tableName, "credential_name")
	_serviceCredential.CredentialKind = field.NewString(tableName, "credential_kind")
	_serviceCredential.Username = field.NewString(tableName, "username")
	_serviceCredential.SecretCiphertext = field.NewString(tableName, "secret_ciphertext")
	_serviceCredential.CertificatePemCiphertext = field.NewString(tableName, "certificate_pem_ciphertext")
	_serviceCredential.PrivateKeyPemCiphertext = field.NewString(tableName, "private_key_pem_ciphertext")
	_serviceCredential.PassphraseCiphertext = field.NewString(tableName, "passphrase_ciphertext")
	_serviceCredential.Status = field.NewString(tableName, "status")
	_serviceCredential.Description = field.NewString(tableName, "description")
	_serviceCredential.CreatedAt = field.NewTime(tableName, "created_at")
	_serviceCredential.UpdatedAt = field.NewTime(tableName, "updated_at")

	_serviceCredential.fillFieldMap()

	return _serviceCredential
}

type serviceCredential struct {
	serviceCredentialDo serviceCredentialDo

	ALL                      field.Asterisk
	ID                       field.Uint64
	ServiceID                field.Uint64
	AccountName              field.String
	CredentialName           field.String
	CredentialKind           field.String
	Username                 field.String
	SecretCiphertext         field.String
	CertificatePemCiphertext field.String
	PrivateKeyPemCiphertext  field.String
	PassphraseCiphertext     field.String
	Status                   field.String
	Description              field.String
	CreatedAt                field.Time
	UpdatedAt                field.Time

	fieldMap map[string]field.Expr
}

func (s serviceCredential) Table(newTableName string) *serviceCredential {
	s.serviceCredentialDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s serviceCredential) As(alias string) *serviceCredential {
	s.serviceCredentialDo.DO = *(s.serviceCredentialDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *serviceCredential) updateTableName(table string) *serviceCredential {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewUint64(table, "id")
	s.ServiceID = field.NewUint64(table, "service_id")
	s.AccountName = field.NewString(table, "account_name")
	s.CredentialName = field.NewString(table, "credential_name")
	s.CredentialKind = field.NewString(table, "credential_kind")
	s.Username = field.NewString(table, "username")
	s.SecretCiphertext = field.NewString(table, "secret_ciphertext")
	s.CertificatePemCiphertext = field.NewString(table, "certificate_pem_ciphertext")
	s.PrivateKeyPemCiphertext = field.NewString(table, "private_key_pem_ciphertext")
	s.PassphraseCiphertext = field.NewString(table, "passphrase_ciphertext")
	s.Status = field.NewString(table, "status")
	s.Description = field.NewString(table, "description")
	s.CreatedAt = field.NewTime(table, "created_at")
	s.UpdatedAt = field.NewTime(table, "updated_at")

	s.fillFieldMap()

	return s
}

func (s *serviceCredential) WithContext(ctx context.Context) IServiceCredentialDo {
	return s.serviceCredentialDo.WithContext(ctx)
}

func (s serviceCredential) TableName() string { return s.serviceCredentialDo.TableName() }

func (s serviceCredential) Alias() string { return s.serviceCredentialDo.Alias() }

func (s serviceCredential) Columns(cols ...field.Expr) gen.Columns {
	return s.serviceCredentialDo.Columns(cols...)
}

func (s *serviceCredential) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *serviceCredential) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 14)
	s.fieldMap["id"] = s.ID
	s.fieldMap["service_id"] = s.ServiceID
	s.fieldMap["account_name"] = s.AccountName
	s.fieldMap["credential_name"] = s.CredentialName
	s.fieldMap["credential_kind"] = s.CredentialKind
	s.fieldMap["username"] = s.Username
	s.fieldMap["secret_ciphertext"] = s.SecretCiphertext
	s.fieldMap["certificate_pem_ciphertext"] = s.CertificatePemCiphertext
	s.fieldMap["private_key_pem_ciphertext"] = s.PrivateKeyPemCiphertext
	s.fieldMap["passphrase_ciphertext"] = s.PassphraseCiphertext
	s.fieldMap["status"] = s.Status
	s.fieldMap["description"] = s.Description
	s.fieldMap["created_at"] = s.CreatedAt
	s.fieldMap["updated_at"] = s.UpdatedAt
}

func (s serviceCredential) clone(db *gorm.DB) serviceCredential {
	s.serviceCredentialDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s serviceCredential) replaceDB(db *gorm.DB) serviceCredential {
	s.serviceCredentialDo.ReplaceDB(db)
	return s
}

type serviceCredentialDo struct{ gen.DO }

type IServiceCredentialDo interface {
	gen.SubQuery
	Debug() IServiceCredentialDo
	WithContext(ctx context.Context) IServiceCredentialDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IServiceCredentialDo
	WriteDB() IServiceCredentialDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IServiceCredentialDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IServiceCredentialDo
	Not(conds ...gen.Condition) IServiceCredentialDo
	Or(conds ...gen.Condition) IServiceCredentialDo
	Select(conds ...field.Expr) IServiceCredentialDo
	Where(conds ...gen.Condition) IServiceCredentialDo
	Order(conds ...field.Expr) IServiceCredentialDo
	Distinct(cols ...field.Expr) IServiceCredentialDo
	Omit(cols ...field.Expr) IServiceCredentialDo
	Join(table schema.Tabler, on ...field.Expr) IServiceCredentialDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IServiceCredentialDo
	RightJoin(table schema.Tabler, on ...field.Expr) IServiceCredentialDo
	Group(cols ...field.Expr) IServiceCredentialDo
	Having(conds ...gen.Condition) IServiceCredentialDo
	Limit(limit int) IServiceCredentialDo
	Offset(offset int) IServiceCredentialDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IServiceCredentialDo
	Unscoped() IServiceCredentialDo
	Create(values ...*model.ServiceCredential) error
	CreateInBatches(values []*model.ServiceCredential, batchSize int) error
	Save(values ...*model.ServiceCredential) error
	First() (*model.ServiceCredential, error)
	Take() (*model.ServiceCredential, error)
	Last() (*model.ServiceCredential, error)
	Find() ([]*model.ServiceCredential, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ServiceCredential, err error)
	FindInBatches(result *[]*model.ServiceCredential, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.ServiceCredential) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IServiceCredentialDo
	Assign(attrs ...field.AssignExpr) IServiceCredentialDo
	Joins(fields ...field.RelationField) IServiceCredentialDo
	Preload(fields ...field.RelationField) IServiceCredentialDo
	FirstOrInit() (*model.ServiceCredential, error)
	FirstOrCreate() (*model.ServiceCredential, error)
	FindByPage(offset int, limit int) (result []*model.ServiceCredential, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IServiceCredentialDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s serviceCredentialDo) Debug() IServiceCredentialDo {
	return s.withDO(s.DO.Debug())
}

func (s serviceCredentialDo) WithContext(ctx context.Context) IServiceCredentialDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s serviceCredentialDo) ReadDB() IServiceCredentialDo {
	return s.Clauses(dbresolver.Read)
}

func (s serviceCredentialDo) WriteDB() IServiceCredentialDo {
	return s.Clauses(dbresolver.Write)
}

func (s serviceCredentialDo) Session(config *gorm.Session) IServiceCredentialDo {
	return s.withDO(s.DO.Session(config))
}

func (s serviceCredentialDo) Clauses(conds ...clause.Expression) IServiceCredentialDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s serviceCredentialDo) Returning(value interface{}, columns ...string) IServiceCredentialDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s serviceCredentialDo) Not(conds ...gen.Condition) IServiceCredentialDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s serviceCredentialDo) Or(conds ...gen.Condition) IServiceCredentialDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s serviceCredentialDo) Select(conds ...field.Expr) IServiceCredentialDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s serviceCredentialDo) Where(conds ...gen.Condition) IServiceCredentialDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s serviceCredentialDo) Order(conds ...field.Expr) IServiceCredentialDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s serviceCredentialDo) Distinct(cols ...field.Expr) IServiceCredentialDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s serviceCredentialDo) Omit(cols ...field.Expr) IServiceCredentialDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s serviceCredentialDo) Join(table schema.Tabler, on ...field.Expr) IServiceCredentialDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s serviceCredentialDo) LeftJoin(table schema.Tabler, on ...field.Expr) IServiceCredentialDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s serviceCredentialDo) RightJoin(table schema.Tabler, on ...field.Expr) IServiceCredentialDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s serviceCredentialDo) Group(cols ...field.Expr) IServiceCredentialDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s serviceCredentialDo) Having(conds ...gen.Condition) IServiceCredentialDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s serviceCredentialDo) Limit(limit int) IServiceCredentialDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s serviceCredentialDo) Offset(offset int) IServiceCredentialDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s serviceCredentialDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IServiceCredentialDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s serviceCredentialDo) Unscoped() IServiceCredentialDo {
	return s.withDO(s.DO.Unscoped())
}

func (s serviceCredentialDo) Create(values ...*model.ServiceCredential) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s serviceCredentialDo) CreateInBatches(values []*model.ServiceCredential, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s serviceCredentialDo) Save(values ...*model.ServiceCredential) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s serviceCredentialDo) First() (*model.ServiceCredential, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ServiceCredential), nil
	}
}

func (s serviceCredentialDo) Take() (*model.ServiceCredential, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ServiceCredential), nil
	}
}

func (s serviceCredentialDo) Last() (*model.ServiceCredential, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ServiceCredential), nil
	}
}

func (s serviceCredentialDo) Find() ([]*model.ServiceCredential, error) {
	result, err := s.DO.Find()
	return result.([]*model.ServiceCredential), err
}

func (s serviceCredentialDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ServiceCredential, err error) {
	buf := make([]*model.ServiceCredential, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s serviceCredentialDo) FindInBatches(result *[]*model.ServiceCredential, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s serviceCredentialDo) Attrs(attrs ...field.AssignExpr) IServiceCredentialDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s serviceCredentialDo) Assign(attrs ...field.AssignExpr) IServiceCredentialDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s serviceCredentialDo) Joins(fields ...field.RelationField) IServiceCredentialDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s serviceCredentialDo) Preload(fields ...field.RelationField) IServiceCredentialDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s serviceCredentialDo) FirstOrInit() (*model.ServiceCredential, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ServiceCredential), nil
	}
}

func (s serviceCredentialDo) FirstOrCreate() (*model.ServiceCredential, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ServiceCredential), nil
	}
}

func (s serviceCredentialDo) FindByPage(offset int, limit int) (result []*model.ServiceCredential, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s serviceCredentialDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s serviceCredentialDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s serviceCredentialDo) Delete(models ...*model.ServiceCredential) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *serviceCredentialDo) withDO(do gen.Dao) *serviceCredentialDo {
	s.DO = *do.(*gen.DO)
	return s
}
