// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"irms/backend/internal/model"
)

func newServiceEnvironment(db *gorm.DB, opts ...gen.DOOption) serviceEnvironment {
	_serviceEnvironment := serviceEnvironment{}

	_serviceEnvironment.serviceEnvironmentDo.UseDB(db, opts...)
	_serviceEnvironment.serviceEnvironmentDo.UseModel(&model.ServiceEnvironment{})

	tableName := _serviceEnvironment.serviceEnvironmentDo.TableName()
	_serviceEnvironment.ALL = field.NewAsterisk(tableName)
	_serviceEnvironment.ID = field.NewUint64(tableName, "id")
	_serviceEnvironment.ServiceID = field.NewUint64(tableName, "service_id")
	_serviceEnvironment.EnvironmentID = field.NewUint64(tableName, "environment_id")
	_serviceEnvironment.CreatedAt = field.NewTime(tableName, "created_at")

	_serviceEnvironment.fillFieldMap()

	return _serviceEnvironment
}

type serviceEnvironment struct {
	serviceEnvironmentDo serviceEnvironmentDo

	ALL           field.Asterisk
	ID            field.Uint64
	ServiceID     field.Uint64
	EnvironmentID field.Uint64
	CreatedAt     field.Time

	fieldMap map[string]field.Expr
}

func (s serviceEnvironment) Table(newTableName string) *serviceEnvironment {
	s.serviceEnvironmentDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s serviceEnvironment) As(alias string) *serviceEnvironment {
	s.serviceEnvironmentDo.DO = *(s.serviceEnvironmentDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *serviceEnvironment) updateTableName(table string) *serviceEnvironment {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewUint64(table, "id")
	s.ServiceID = field.NewUint64(table, "service_id")
	s.EnvironmentID = field.NewUint64(table, "environment_id")
	s.CreatedAt = field.NewTime(table, "created_at")

	s.fillFieldMap()

	return s
}

func (s *serviceEnvironment) WithContext(ctx context.Context) IServiceEnvironmentDo {
	return s.serviceEnvironmentDo.WithContext(ctx)
}

func (s serviceEnvironment) TableName() string { return s.serviceEnvironmentDo.TableName() }

func (s serviceEnvironment) Alias() string { return s.serviceEnvironmentDo.Alias() }

func (s serviceEnvironment) Columns(cols ...field.Expr) gen.Columns {
	return s.serviceEnvironmentDo.Columns(cols...)
}

func (s *serviceEnvironment) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *serviceEnvironment) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 4)
	s.fieldMap["id"] = s.ID
	s.fieldMap["service_id"] = s.ServiceID
	s.fieldMap["environment_id"] = s.EnvironmentID
	s.fieldMap["created_at"] = s.CreatedAt
}

func (s serviceEnvironment) clone(db *gorm.DB) serviceEnvironment {
	s.serviceEnvironmentDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s serviceEnvironment) replaceDB(db *gorm.DB) serviceEnvironment {
	s.serviceEnvironmentDo.ReplaceDB(db)
	return s
}

type serviceEnvironmentDo struct{ gen.DO }

type IServiceEnvironmentDo interface {
	gen.SubQuery
	Debug() IServiceEnvironmentDo
	WithContext(ctx context.Context) IServiceEnvironmentDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IServiceEnvironmentDo
	WriteDB() IServiceEnvironmentDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IServiceEnvironmentDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IServiceEnvironmentDo
	Not(conds ...gen.Condition) IServiceEnvironmentDo
	Or(conds ...gen.Condition) IServiceEnvironmentDo
	Select(conds ...field.Expr) IServiceEnvironmentDo
	Where(conds ...gen.Condition) IServiceEnvironmentDo
	Order(conds ...field.Expr) IServiceEnvironmentDo
	Distinct(cols ...field.Expr) IServiceEnvironmentDo
	Omit(cols ...field.Expr) IServiceEnvironmentDo
	Join(table schema.Tabler, on ...field.Expr) IServiceEnvironmentDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IServiceEnvironmentDo
	RightJoin(table schema.Tabler, on ...field.Expr) IServiceEnvironmentDo
	Group(cols ...field.Expr) IServiceEnvironmentDo
	Having(conds ...gen.Condition) IServiceEnvironmentDo
	Limit(limit int) IServiceEnvironmentDo
	Offset(offset int) IServiceEnvironmentDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IServiceEnvironmentDo
	Unscoped() IServiceEnvironmentDo
	Create(values ...*model.ServiceEnvironment) error
	CreateInBatches(values []*model.ServiceEnvironment, batchSize int) error
	Save(values ...*model.ServiceEnvironment) error
	First() (*model.ServiceEnvironment, error)
	Take() (*model.ServiceEnvironment, error)
	Last() (*model.ServiceEnvironment, error)
	Find() ([]*model.ServiceEnvironment, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ServiceEnvironment, err error)
	FindInBatches(result *[]*model.ServiceEnvironment, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.ServiceEnvironment) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IServiceEnvironmentDo
	Assign(attrs ...field.AssignExpr) IServiceEnvironmentDo
	Joins(fields ...field.RelationField) IServiceEnvironmentDo
	Preload(fields ...field.RelationField) IServiceEnvironmentDo
	FirstOrInit() (*model.ServiceEnvironment, error)
	FirstOrCreate() (*model.ServiceEnvironment, error)
	FindByPage(offset int, limit int) (result []*model.ServiceEnvironment, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IServiceEnvironmentDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s serviceEnvironmentDo) Debug() IServiceEnvironmentDo {
	return s.withDO(s.DO.Debug())
}

func (s serviceEnvironmentDo) WithContext(ctx context.Context) IServiceEnvironmentDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s serviceEnvironmentDo) ReadDB() IServiceEnvironmentDo {
	return s.Clauses(dbresolver.Read)
}

func (s serviceEnvironmentDo) WriteDB() IServiceEnvironmentDo {
	return s.Clauses(dbresolver.Write)
}

func (s serviceEnvironmentDo) Session(config *gorm.Session) IServiceEnvironmentDo {
	return s.withDO(s.DO.Session(config))
}

func (s serviceEnvironmentDo) Clauses(conds ...clause.Expression) IServiceEnvironmentDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s serviceEnvironmentDo) Returning(value interface{}, columns ...string) IServiceEnvironmentDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s serviceEnvironmentDo) Not(conds ...gen.Condition) IServiceEnvironmentDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s serviceEnvironmentDo) Or(conds ...gen.Condition) IServiceEnvironmentDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s serviceEnvironmentDo) Select(conds ...field.Expr) IServiceEnvironmentDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s serviceEnvironmentDo) Where(conds ...gen.Condition) IServiceEnvironmentDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s serviceEnvironmentDo) Order(conds ...field.Expr) IServiceEnvironmentDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s serviceEnvironmentDo) Distinct(cols ...field.Expr) IServiceEnvironmentDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s serviceEnvironmentDo) Omit(cols ...field.Expr) IServiceEnvironmentDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s serviceEnvironmentDo) Join(table schema.Tabler, on ...field.Expr) IServiceEnvironmentDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s serviceEnvironmentDo) LeftJoin(table schema.Tabler, on ...field.Expr) IServiceEnvironmentDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s serviceEnvironmentDo) RightJoin(table schema.Tabler, on ...field.Expr) IServiceEnvironmentDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s serviceEnvironmentDo) Group(cols ...field.Expr) IServiceEnvironmentDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s serviceEnvironmentDo) Having(conds ...gen.Condition) IServiceEnvironmentDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s serviceEnvironmentDo) Limit(limit int) IServiceEnvironmentDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s serviceEnvironmentDo) Offset(offset int) IServiceEnvironmentDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s serviceEnvironmentDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IServiceEnvironmentDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s serviceEnvironmentDo) Unscoped() IServiceEnvironmentDo {
	return s.withDO(s.DO.Unscoped())
}

func (s serviceEnvironmentDo) Create(values ...*model.ServiceEnvironment) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s serviceEnvironmentDo) CreateInBatches(values []*model.ServiceEnvironment, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s serviceEnvironmentDo) Save(values ...*model.ServiceEnvironment) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s serviceEnvironmentDo) First() (*model.ServiceEnvironment, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ServiceEnvironment), nil
	}
}

func (s serviceEnvironmentDo) Take() (*model.ServiceEnvironment, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ServiceEnvironment), nil
	}
}

func (s serviceEnvironmentDo) Last() (*model.ServiceEnvironment, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ServiceEnvironment), nil
	}
}

func (s serviceEnvironmentDo) Find() ([]*model.ServiceEnvironment, error) {
	result, err := s.DO.Find()
	return result.([]*model.ServiceEnvironment), err
}

func (s serviceEnvironmentDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ServiceEnvironment, err error) {
	buf := make([]*model.ServiceEnvironment, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s serviceEnvironmentDo) FindInBatches(result *[]*model.ServiceEnvironment, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s serviceEnvironmentDo) Attrs(attrs ...field.AssignExpr) IServiceEnvironmentDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s serviceEnvironmentDo) Assign(attrs ...field.AssignExpr) IServiceEnvironmentDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s serviceEnvironmentDo) Joins(fields ...field.RelationField) IServiceEnvironmentDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s serviceEnvironmentDo) Preload(fields ...field.RelationField) IServiceEnvironmentDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s serviceEnvironmentDo) FirstOrInit() (*model.ServiceEnvironment, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ServiceEnvironment), nil
	}
}

func (s serviceEnvironmentDo) FirstOrCreate() (*model.ServiceEnvironment, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ServiceEnvironment), nil
	}
}

func (s serviceEnvironmentDo) FindByPage(offset int, limit int) (result []*model.ServiceEnvironment, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s serviceEnvironmentDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s serviceEnvironmentDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s serviceEnvironmentDo) Delete(models ...*model.ServiceEnvironment) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *serviceEnvironmentDo) withDO(do gen.Dao) *serviceEnvironmentDo {
	s.DO = *do.(*gen.DO)
	return s
}
